### ISSUE TITLE
problemas en ambiente de desarrollo con docker + wordpress + woocommerce

### ISSUE THREAD

**Issue by berchj** [AfipSDK/afip.php#100]
Hola! estoy utilizando un docker para correr un wordpress + woocommerce (tengo el class SOAP activo) pero no encuentro la manera de hacer funcionar la libreria ... la idea es validar la inscripcion de la persona con su CUIT 
![image](https://user-images.githubusercontent.com/47766727/115062343-a2f7f280-9ec0-11eb-98d7-ea7351038a0b.png)
ese es el error que tira ... intenté hacer 
soap.wsdl_cache_enabled = 0
soap.wsdl_cache_ttl = 0
en mi php.ini 
tambien con phpinfo(); verifiqué que se instaló SOAP correctamente -> 
![image](https://user-images.githubusercontent.com/47766727/115063105-8314fe80-9ec1-11eb-8d18-49bb2c8de1e1.png)

alguna idea? gracias...

**Comment by ivanalemunioz** [comment]
Parece que no se puede conectar con el ws. Deberias confirmar que el request este saliendo, quiza docker lo bloquea o algo

**Comment by berchj** [comment]
Definitivamente tiene que ver algo con el docker, ya que la libreria me funcionó perfecto con LAMPP en localhost

**Comment by ivanalemunioz** [comment]
Pudiste dar con el problema??
