### ISSUE TITLE
Error SOAP Fault: HTTP Service Unavailable 

### ISSUE THREAD

**Issue by EscuderoKevin93** [AfipSDK/afip.php#101]
Hola buenos dias, hoy a la mañana hice como 30 facturas sin problemas y de la nada me empezo a tirar este error y no me deja hacer factura electronica, ni preguntar el estado del servidor nada.

Sera problema de AFIP ? pero yo puedo entrar a la web normalmente.

Fatal error: Uncaught Exception: SOAP Fault: HTTP Service Unavailable in C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Afip.php:405 Stack trace: #0 C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Afip.php(385): AfipWebService->_CheckErrors('FEDummy', Object(SoapFault)) #1 C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Class\ElectronicBilling.php(322): AfipWebService->ExecuteRequest('FEDummy', Array) #2 C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Class\ElectronicBilling.php(291): ElectronicBilling->ExecuteRequest('FEDummy') #3 C:\xampp\htdocs\kevin\afip.php(15): ElectronicBilling->GetServerStatus() #4 {main} thrown in C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Afip.php on line 405

**Comment by NicoMachado** [comment]
La web y el web service son equipos distintos, espero!
En un cliente mío tuvo el mismo error.
Asumo que es el servicio web que se ha caído.

**Comment by NicoMachado** [comment]
Creo q con esta URL podes verficar si esta caido o no...

https://servicios1.afip.gov.ar/wsfev1/service.asmx?op=FEDummy

a las 11:42 del 26/4, no responde

**Comment by EscuderoKevin93** [comment]
Bueno muchas gracias, me quedo mas tranquilo.
