### ISSUE TITLE
PeriodoAsoc

### ISSUE THREAD

**Issue by grpujol** [AfipSDK/afip.php#103]
Primero que nada felicitar a los creadores de esta librería, es una maravilla!
tengo que hacer una nota de crédito, pero lo que tengo para enviar son los periodos asociados, ya le agregue al $data los valores:

> $data['PeriodoAsoc'] = array( 'FchDesde' => intval(date('Ymd')), 'FchHasta' => intval(date('Ymd')) );

Me sigue dando el mismo error:

> Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.

Intuyo que tengo que agregar esos campos también en el wsfe.wsdl, intenté agregarlos copiando, toqueteando y pegando CbteAsoc:

      <s:complexType name="PeriodoAsoc">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="FchDesde" type="s:string"/>
          <s:element minOccurs="1" maxOccurs="1" name="FchHasta" type="s:string"/>
        </s:sequence>
      </s:complexType>

¿Alguien me puede orientar un poco en como seguir o que me falta...?
Desde ya muchas gracias

**Comment by ivanalemunioz** [comment]
Faltaba actualizar los WSDL, ya estan en la ultima actualizacion!

**Comment by grpujol** [comment]
¡Gracias capo!

**Comment by lucianobosco** [comment]
Hola @ivanalemunioz , puede ser que el archivo de ejemplo este desactualizado?
https://github.com/AfipSDK/afip.php/blob/master/examples/CreateVoucher.php

**Comment by ivanalemunioz** [comment]
Asi es
