### ISSUE TITLE
error 500 al ejecutar ExecuteRequest

### ISSUE THREAD

**Issue by mdettoni** [AfipSDK/afip.php#106]
Buenas tardes, ante cualquier consulta que haga tira error 500 al ejecutar ExecuteRequest

Este es el resultado de hacer var_dump previo a la llamada

object(SoapClient)#3 (6) { ["location"]=> string(47) "https://wswhomo.afip.gov.ar/wsfev1/service.asmx" ["trace"]=> int(1) ["_exceptions"]=> bool(false) ["_stream_context"]=> resource(5) of type (stream-context) ["_soap_version"]=> int(2) ["sdl"]=> resource(7) of type (SOAP SDL) }

Alguna idea?
gracias

**Comment by ivanalemunioz** [comment]
Agregale estas lineas antes del codigo para que muestre detalles de los errores

```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

```

**Comment by mdettoni** [comment]
Gracias, prueba básica, mala mía, faltaban permisos de escritura para generar el archivo xml
