### ISSUE TITLE
Luego de instalar los certificados no se como continuar.

### ISSUE THREAD

**Issue by jpablocas** [AfipSDK/afip.php#107]
Hola Ivan. ya copie los cert y key de Afip con mi cuit. Luego copie al comiezo del Afip.php  include 'ruta/Afip.php'; $CUIT =xxxxxxx; $afip = new Afip(array('CUIT' => $CUIT));
Luego de esto, no se como continuar. Como genero una facturaB ? y en Afip donde puedo comprobar si en el entorno TEST se genero? perdon. me perdi en esta parte.

**Comment by AndyGotfridt** [comment]
Hola! Debes especificar si estas en entorno de prueba / producción ([Primeros Pasos](https://github.com/AfipSDK/afip.php/wiki/Primeros-pasos)). Recordá que los Certificados son diferentes.
Después para hacer una factura acá tenes un ejemplo de FB 
[Crear y asignar CAE a un comprobante](https://github.com/AfipSDK/afip.php/wiki/Facturaci%C3%B3n-Electr%C3%B3nica#crear-y-asignar-cae-a-un-comprobante)

**Comment by jpablocas** [comment]
Gracias Andy. Lei toda la documentacion pero sigo sin poder emitir un factura. Hay algun ejemplo en algun lado para descargar en donde solo se deba colocar los certificados y reemplazar el cuit en el codigo y se puede probar ?

Enviado desde mi Samsung Mobile de Claro
Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by AndyGotfridt** [comment]
El ejemplo que te adjunte. Tenés que agregarle los datos CUIT, CERTIFICADOS
y Si estás en modo producción. Si puedo te adjunto como deberías pasarle
los datos, aunque esta bastante claro

**Comment by AndyGotfridt** [comment]
`$afip = new Afip(array('CUIT' => CUIT,'cert' => '.crt','key' => 'key','production' => false/true));`
después lo empalmas con lo de la guia
`$data = array(
	'CantReg' 	=> 1,  // Cantidad de comprobantes a registrar
	'PtoVta' 	=> 1,  // Punto de venta
	'CbteTipo' 	=> 6,  // Tipo de comprobante (ver tipos disponibles) 
	'Concepto' 	=> 1,  // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
	'DocTipo' 	=> 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles)
	'DocNro' 	=> 0,  // Número de documento del comprador (0 consumidor final)
	'CbteDesde' 	=> 1,  // Número de comprobante o numero del primer comprobante en caso de ser mas de uno
	'CbteHasta' 	=> 1,  // Número de comprobante o numero del último comprobante en caso de ser mas de uno
	'CbteFch' 	=> intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
	'ImpTotal' 	=> 121, // Importe total del comprobante
	'ImpTotConc' 	=> 0,   // Importe neto no gravado
	'ImpNeto' 	=> 100, // Importe neto gravado
	'ImpOpEx' 	=> 0,   // Importe exento de IVA
	'ImpIVA' 	=> 21,  //Importe total de IVA
	'ImpTrib' 	=> 0,   //Importe total de tributos
	'MonId' 	=> 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos) 
	'MonCotiz' 	=> 1,     // Cotización de la moneda usada (1 para pesos argentinos)  
	'Iva' 		=> array( // (Opcional) Alícuotas asociadas al comprobante
		array(
			'Id' 		=> 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles) 
			'BaseImp' 	=> 100, // Base imponible
			'Importe' 	=> 21 // Importe 
		)
	), 
);

$res = $afip->ElectronicBilling->CreateVoucher($data);

echo $res['CAE']; //CAE asignado el comprobante
echo $res['CAEFchVto']; //Fecha de vencimiento del CAE (yyyy-mm-dd)`

OJO Fíjate como instancias vos la clase de AFIP, asi te debería funcionar

**Comment by AndyGotfridt** [comment]
`$afip = new Afip(array('CUIT' => CUIT,'cert' => '.crt','key' => 'key','production' => false/true));`
después lo empalmas con lo de la guia
````$data = array(
	'CantReg' 	=> 1,  // Cantidad de comprobantes a registrar
	'PtoVta' 	=> 1,  // Punto de venta
	'CbteTipo' 	=> 6,  // Tipo de comprobante (ver tipos disponibles) 
	'Concepto' 	=> 1,  // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
	'DocTipo' 	=> 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles)
	'DocNro' 	=> 0,  // Número de documento del comprador (0 consumidor final)
	'CbteDesde' 	=> 1,  // Número de comprobante o numero del primer comprobante en caso de ser mas de uno
	'CbteHasta' 	=> 1,  // Número de comprobante o numero del último comprobante en caso de ser mas de uno
	'CbteFch' 	=> intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
	'ImpTotal' 	=> 121, // Importe total del comprobante
	'ImpTotConc' 	=> 0,   // Importe neto no gravado
	'ImpNeto' 	=> 100, // Importe neto gravado
	'ImpOpEx' 	=> 0,   // Importe exento de IVA
	'ImpIVA' 	=> 21,  //Importe total de IVA
	'ImpTrib' 	=> 0,   //Importe total de tributos
	'MonId' 	=> 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos) 
	'MonCotiz' 	=> 1,     // Cotización de la moneda usada (1 para pesos argentinos)  
	'Iva' 		=> array( // (Opcional) Alícuotas asociadas al comprobante
		array(
			'Id' 		=> 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles) 
			'BaseImp' 	=> 100, // Base imponible
			'Importe' 	=> 21 // Importe 
		)
	), 
);

$res = $afip->ElectronicBilling->CreateVoucher($data);

echo $res['CAE']; //CAE asignado el comprobante
echo $res['CAEFchVto']; //Fecha de vencimiento del CAE (yyyy-mm-dd)````

OJO Fíjate como instancias vos la clase de AFIP, asi te debería funcionar

**Comment by AndyGotfridt** [comment]
`$afip = new Afip(array('CUIT' => CUIT,'cert' => '.crt','key' => 'key','production' => false/true));`
después lo empalmas con lo de la guia
````
$data = array(
	'CantReg' 	=> 1,  // Cantidad de comprobantes a registrar
	'PtoVta' 	=> 1,  // Punto de venta
	'CbteTipo' 	=> 6,  // Tipo de comprobante (ver tipos disponibles) 
	'Concepto' 	=> 1,  // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
	'DocTipo' 	=> 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles)
	'DocNro' 	=> 0,  // Número de documento del comprador (0 consumidor final)
	'CbteDesde' 	=> 1,  // Número de comprobante o numero del primer comprobante en caso de ser mas de uno
	'CbteHasta' 	=> 1,  // Número de comprobante o numero del último comprobante en caso de ser mas de uno
	'CbteFch' 	=> intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
	'ImpTotal' 	=> 121, // Importe total del comprobante
	'ImpTotConc' 	=> 0,   // Importe neto no gravado
	'ImpNeto' 	=> 100, // Importe neto gravado
	'ImpOpEx' 	=> 0,   // Importe exento de IVA
	'ImpIVA' 	=> 21,  //Importe total de IVA
	'ImpTrib' 	=> 0,   //Importe total de tributos
	'MonId' 	=> 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos) 
	'MonCotiz' 	=> 1,     // Cotización de la moneda usada (1 para pesos argentinos)  
	'Iva' 		=> array( // (Opcional) Alícuotas asociadas al comprobante
		array(
			'Id' 		=> 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles) 
			'BaseImp' 	=> 100, // Base imponible
			'Importe' 	=> 21 // Importe 
		)
	), 
);

$res = $afip->ElectronicBilling->CreateVoucher($data);

echo $res['CAE']; //CAE asignado el comprobante
echo $res['CAEFchVto']; //Fecha de vencimiento del CAE (yyyy-mm-dd)

**Comment by AndyGotfridt** [comment]
Obviamente es un ejemplo genérico, debes adaptarlo a tus necesidades y armar toda la lógica que requieras

**Comment by jpablocas** [comment]
Ok lo voy a probar. Si me funciona. Luego para salir en produccion, cual es el valor para tener un soporte pro x 30 dias.

Enviado desde mi Samsung Mobile de Claro
Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by AndyGotfridt** [comment]
No tengo idea. Eso tenés que verlo con Iván. Creo que el brinda el soporte

**Comment by jpablocas** [comment]
lo ejecute asi como lo adjunto, y me aparece pantalla en blanco o por consola nada. ningun error.
estoy con php 7.1

________________________________
De: Andy Gotfridt ***@***.***>
Enviado: martes, 15 de junio de 2021 20:04
Para: AfipSDK/afip.php ***@***.***>
Cc: jpablocas ***@***.***>; Author ***@***.***>
Asunto: Re: [AfipSDK/afip.php] Luego de instalar los certificados no se como continuar. (#107)


No tengo idea. Eso tenés que verlo con Iván. Creo que el brinda el soporte

**Comment by AndyGotfridt** [comment]
Fijate como llamas a la libreria, si la usas con composer, si la llamas requiriendo la class. Asi como te lo pase te tiene que funcionar el ejemplo basico

**Comment by jpablocas** [comment]
perfectooo me funciono. esta mal el nombre del certificado.
ultima pregunta, como veo la factura que acabo de generar en afip si esta correctamente emitida en el entorno TEST?
mil gracias x todo !!!! son un crack.

________________________________
De: Andy Gotfridt ***@***.***>
Enviado: martes, 15 de junio de 2021 20:58
Para: AfipSDK/afip.php ***@***.***>
Cc: jpablocas ***@***.***>; Author ***@***.***>
Asunto: Re: [AfipSDK/afip.php] Luego de instalar los certificados no se como continuar. (#107)


Fijate como llamas a la libreria, si la usas con composer, si la llamas requiriendo la class. Asi como te lo pase te tiene que funcionar el ejemplo basico
