### ISSUE TITLE
Alquien tiene el templete de Factura B AFIP con FPDF ?

### ISSUE THREAD

**Issue by jpablocas** [AfipSDK/afip.php#108]

**Comment by kbzone** [comment]
hola,

intenta agregar una descripción al problema que estás teniendo para que podamos ayudarte mejor.

leyendo el título, imagino que lo que buscás es poder generar un pdf, utilizando un template.

yo lo tengo implementado de la siguiente manera:
https://gist.github.com/kbzone/bf2ce551f3434819fdcc65d35f47f0d0#file-pdf_generator-php

analiza el código, impleméntalo y avísanos si te sirve.

**Comment by Askeshine** [comment]
Por lo que entendi el quiere la factura diseñada en PDF la cual yo tampoco pude lograr dado que lleva mucho codigo manual por lo que vi vos ahi estas usando un template y escribis sobre las coordenadas directamente ? como haces cuando la cantidad de articulos supera los limites de tu factura ? 

> 
> 
> hola,
> 
> intenta agregar una descripción al problema que estás teniendo para que podamos ayudarte mejor.
> 
> leyendo el título, imagino que lo que buscás es poder generar un pdf, utilizando un template.
> 
> yo lo tengo implementado de la siguiente manera:
> https://gist.github.com/kbzone/bf2ce551f3434819fdcc65d35f47f0d0#file-pdf_generator-php
> 
> analiza el código, impleméntalo y avísanos si te sirve.

**Comment by kbzone** [comment]
ahh, entonces mi aporte no tuvo sentido. disculpas.

con respecto a tu pregunta, mi caso de uso es muy simple, siempre es una sola línea porque es un sólo servicio.

básicamente me pidieron un sistema que automatice desde una planilla de excel los pagos a la afip. y nada más.

saludos
