### ISSUE TITLE
Error al implementar - openssl_pkcs7_sign(): error getting cert in 

### ISSUE THREAD

**Issue by rlezamacn** [AfipSDK/afip.php#109]
Estoy implementando el sdk, en estos momentos me genera este error:
 openssl_pkcs7_sign(): error getting cert 

He realizado el cambio de long a string,
He agregado el realpath

Alguien me puede ayudar, por favor?

El servidor es windows server, y utilizo iiss.

**Comment by ivanalemunioz** [comment]
Tu cert comienza con BEGIN CERTIFICATE o BEGIN CERTIFICATE REQUEST?

**Comment by rlezamacn** [comment]
El problema estaba en regresar todo el CUIT a long  sin tocar esa parte del sdk.

Recomiendo usar el crt y la privada.key generada en vez de copiar el contenido en los archivos cert y key del sdk. Ejm:

     $afip = new Afip([
            'CUIT'=> 1111111111, //<-- ojo ahi que siga siendo logn!
            'cert' => 'APPEESSTEST.crt',
            'key'=> 'privada.key'
            ]);
 Gracias.

**Comment by rodrigocataffo** [comment]
> 

A mi me pasa lo mismo. En homologación mi certificado comenzaba con BEGIN CERTIFICATE y el de Prod, que ahora no funciona, comienza con BEGIN CERTIFICATE REQUEST. Hay algún problema con eso?

Gracias!

**Comment by rodrigocataffo** [comment]
> Tu cert comienza con BEGIN CERTIFICATE o BEGIN CERTIFICATE REQUEST?

A mi me pasa lo mismo. En homologación mi certificado comenzaba con BEGIN CERTIFICATE y el de Prod, que ahora no funciona, comienza con BEGIN CERTIFICATE REQUEST. Hay algún problema con eso?

Gracias!

**Comment by ivanalemunioz** [comment]
Si dice BEGIN CERTIFICATE REQUEST es porque no es el certificado, es el CERTIFICATE REQUEST, el certificado es el que descargas de la pagina de afip
