### ISSUE TITLE
Errores en los certificados al pasar de desarrollo a produción.

### ISSUE THREAD

**Issue by arodriguezpetit** [AfipSDK/afip.php#111]
Tengo un sistema de facturación con vuestra librería, funcionando perfecto, pero al pasar a producción con los correspondientes certificados, comenzaron los errores.

Con el primer certificado obtengo el siguiente error

Warning: openssl_pkcs7_sign(): error creating PKCS7 structure! in Afip.php on line 208

Genere dos certificados más en Afip, pensando que podría tener error en el mismo, en ambos certificados obtengo un error diferente al anterior, pero igual entre estos últimos certificados.

Fatal error: Uncaught Exception: SOAP Fault: ns1:coe.not Authorized Computador no autorizado a acceder al servicio in Afip.php:231

**Revisando varios posteos aquí en github y en foros se verifico también:**

1. Colocar true en producción en el array de inicialización del objeto afip y tratar al cuit tanto como string o como int o long.
2. Los archivos de los propios certificados, que fueran correctos, sin espacios dentro de los mismos.
3. Los permisos del directorio de los certificados y los permisos de los propios certificados.
4. Cambiar los nombres del directorio de los certificados y los nombres de los mismos, declarándolos en el array de inicialización del objeto afip.
5. Fecha y hora del equipo y sincronismo con el servidor horario de Afip (time.afip.gov.ar).

**Comment by ivanalemunioz** [comment]
Le estas pasando el parametro `production => true` ? en el new Afip

**Comment by arodriguezpetit** [comment]
Si, lo comente en el punto 1

$afip = new Afip( 
    array(
    'CUIT' => $cuit, 
    'production' => TRUE, 
    'res_folder' => '/Certificado/', 
    'key' => 'llave.key', 
    'cert' => 'Facturacion2.crt'    
    ) 
);

**Comment by ivanalemunioz** [comment]
Ah sisi me confundi de error, te falta darle permiso al certificado para que utilize ese ws

**Comment by arodriguezpetit** [comment]
¿En que parte de la página de Afip lo haces?, todo lo que encontré es viejo y referencia a partes de la página que ya no existe.

**Comment by arodriguezpetit** [comment]
Solucionado, certificado con problemas, se creo y autorizo otro certificado y ese funciono.
En un momento apareció un error de maquina no autorizado para funcionar, pero el problema es que no es correcto el mensaje de la Afip.

Al armar el array afip, se tomaban datos de una base de configuración, de la siguiente manera:

       $afip = new Afip(
                array(
                'CUIT' => $cuit,
                'production' => $estado_fiscal, //aquí se enviá un TRUE o FALSE según se este en producción o desarrollo
                )
            );

Después de varias pruebas, se noto que había que modificar la linea de production agregando un boolval, quedando asi:
           'production' => boolval($estado_fiscal),
Con eso se evita el error de maquina no autorizada.
