### ISSUE TITLE
feature request: campo descripción en voucher de tipo servicio

### ISSUE THREAD

**Issue by kbzone** [AfipSDK/afip.php#113]
hola! técnicamente no es un problema, pero mi cliente cuando carga una nueva factura de forma manual desde la web (recibo c / de tipo Servicio), en el paso 3 le aparece el campo "**Descripción del Servicio**" al lado del campo Precio. busqué en la documentación oficial y aquí, leí en el código fuente del paquete, y al menos yo no pude encontrar cómo configurar ése parámetro para implementarlo en el webservice.

lo más cerca que encontré, fue [éste](https://github.com/AfipSDK/afip.php/issues/85) issue creado por un usuario.

cualquier dato que puedan darme para agregar descripción me serviría un montón.

gracias!

* _offtopic_: sé que se dijo en muchos tickets y que no va con el espíritu de "Issue", pero quería agradecer y felicitar el tremendo laburo que armaron con éste paquete, y liberarlo a la comunidad. muchas gracias!

**Comment by ivanalemunioz** [comment]
Esa descripcion no la pide el web service. Podes agregarla vos en el PDF (o formato que utilizes) que le generas a tu cliente

**Comment by kbzone** [comment]
bien, perfecto.

y por último, estoy teniendo dificultades con respecto al campo "Condiciones de Venta", que tiene como opciones «Contado / Tarjeta de crédito / Cuenta corriente (que es el que necesito)», tampoco se los puede configurar?

**Comment by ivanalemunioz** [comment]
Igual que con los demas campos, lo pone uno en la factura que le presenta al cliente

**Comment by kbzone** [comment]
muchas gracias!

cierro issue.
