### ISSUE TITLE
ERROR RegisterScopeFive->GetTaxpayerDetails($cuit) 

### ISSUE THREAD

**Issue by trio1234** [AfipSDK/afip.php#117]
Hola  chicos  estoy probando el sdk y me sale en al consultar en el  PADRON A5

RegisterScopeFive->GetTaxpayerDetails($cuit) 
**Me devuelve**  Este token no le permite actuar en representacion de
la CUIT...
Estuve mirano llas issues cerradas y  no encuentro nada sobre esto!!!!
Estoy en produccion!
Gracias!

Solo me deja buscar mi propio cuit y me devuelve la informacion **OK**

**Comment by ivanalemunioz** [comment]
En new Afip() estas poniendo siempre tu cuit?

**Comment by ivanalemunioz** [comment]
En `new Afip()` debes dejar tu cuit (o a nombre de quien este  el certificado) siempre, ese no cambia. El cuit que quieras consultar debes ponerlo en `RegisterScopeFive->GetTaxpayerDetails($cuit)`

**Comment by trio1234** [comment]
Efectivamente Ivan , no estaba poniendo el CUIT en los parametros , voy a hardcordearlos en la configuracion , desde ya muchas Gracias!
