### ISSUE TITLE
Laravel use Folder

### ISSUE THREAD

**Issue by gabrieeelsp** [AfipSDK/afip.php#119]
estoy intentando usar la clase Afip.php en laravel 8,

alescribir
use \vendor\afipsdk\afip.php\src\Afip;

me sale el siguiente error,

"message": "syntax error, unexpected '.', expecting ';' or ','",

parece que necesito alguna forma de escapar el caracter '.' dentro de la sintaxis de use

como puedo resolver esto?

**Comment by kbzone** [comment]
si el paquete Afip lo instalaste via composer, nada más tienes que escribir:

`use Afip;`

en los archivos donde vas a usar la clase.

**Comment by gabrieeelsp** [comment]
muchas gracias por la respuesta, 
me sirvio mucho

saludos!!

gabrieeelsp

**Comment by kbzone** [comment]
me alegro,

sería bueno que cierres el ticket,

saludos

**Comment by gabrieeelsp** [comment]
Muchas gracias
