### ISSUE TITLE
Afip caida ?

### ISSUE THREAD

**Issue by Askeshine** [AfipSDK/afip.php#120]
Hola , a alguien mas no le anda desde el dia viernes la AFIP ? va la API no la pagina en si.

**Comment by Askeshine** [comment]
Warning: SoapClient::__doRequest(): SSL: Se ha forzado la interrupci�n de una conexi�n existente por el host remoto. in C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Afip.php on line 383

Fatal error: Uncaught Exception: SOAP Fault: HTTP Error Fetching http headers in C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Afip.php:405 Stack trace: #0 C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Afip.php(385): AfipWebService->_CheckErrors('FECompUltimoAut...', Object(SoapFault)) #1 C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Class\ElectronicBilling.php(322): AfipWebService->ExecuteRequest('FECompUltimoAut...', Array) #2 C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Class\ElectronicBilling.php(41): ElectronicBilling->ExecuteRequest('FECompUltimoAut...', Array) #3 C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Class\ElectronicBilling.php(127): ElectronicBilling->GetLastVoucher(5, 6) #4 C:\xampp\htdocs\kevin\afip.php(42): ElectronicBilling->CreateNextVoucher(Array) #5 {main} thrown in C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Afip.php on line 405

**Comment by ivanalemunioz** [comment]
Si funcionan correctamente, debe se algo de la conexion en tu maquina

**Comment by tr0mpiz** [comment]
yo estoy probando la homologación tambien y ningún problema.
