### ISSUE TITLE
Consulta por DNI en desarrollo? GetTaxIDByDocument

### ISSUE THREAD

**Issue by tr0mpiz** [AfipSDK/afip.php#122]
Buenos dias, queria saber que dni se usaba para traer datos en la consulta de DNI 
$tax_id = $afip->RegisterScopeThirteen->GetTaxIDByDocument($dni) ;

Muchas gracias.

**Comment by ivanalemunioz** [comment]
La idea es usar el dni que necesites consultar

**Comment by tr0mpiz** [comment]
> La idea es usar el dni que necesites consultar

Si entiendo, estuve leyendo que en homologacion hay un CUIT para consultar porque si pones otro no trae datos, estuve probando el DNI con mi DNI y no me trae datos, por eso mi consulta.

**Comment by ivanalemunioz** [comment]
No sabria decirte de uno para dev
