### ISSUE TITLE
AFIP Caida...

### ISSUE THREAD

**Issue by KatiaSishost** [AfipSDK/afip.php#123]
Hola, alguien tiene idea como hacer cuando esta caida la afip? he visto un par de sistemas que emiten igualmente la factura por mas que el sistema de la afip este caida... como Colppy y otros mas.

**Comment by ivanalemunioz** [comment]
Quiza sera que lo guardan en su sistema y reintentan la emision cuando vuelva a estar disponible. En la pagina de colppy vi que dice 

>  Emití tus facturas una única vez, aún si no funciona AFIP. Nosotros hacemos la reconexión automáticamente.

**Comment by juanledesma** [comment]
Si la envía por mail, se emitir cuando el servicio se activa . Pero también esta la posibilidad de obtener los cae de forma anticipada , y luego informar los que se utilizaron . En un principio estaba esa opción, ahora desconozco si sigue habilitada.

Juan Luis Ledesma
11 3622-7826
________________________________

**Comment by ivanalemunioz** [comment]
Habria que ver si cuando esta caida la emite con CAEA o directamente sin autorizacion. Pero si esta caida teoricamente con CAE no la podria emitir
