### ISSUE TITLE
Especificar Condición frente al IVA

### ISSUE THREAD

**Issue by rodrigocataffo** [AfipSDK/afip.php#125]
Buenas!
Quería saber cómo hacer para que al crear la factura por el WS se pueda especificar la condición frente al IVA del cliente, por ej si es IVA Responsable Inscripto, Consumidor Final, etc.

En https://www.afip.gob.ar/fe/ayuda/tablas.asp encontré el listado de estas opciones ("Tipos de Responsable") pero no encontré en ningún lado cómo especificarlo en la creación de la factura ni tampoco como obtener dicho listado via WS.

Muchas gracias desde ya. #

**Comment by ivanalemunioz** [comment]
Eso lo especificas vos en el PDF que le creas al cliente, no se envia la AFIP
