### ISSUE TITLE
Cómo ver los errores y rechazos de AFIP

### ISSUE THREAD

**Issue by thalskarth** [AfipSDK/afip.php#128]
Al ejecutar
`$res = $afip->ElectronicBilling->CreateVoucher($data);`
Suele devolver
```
echo $res['CAE']; //CAE asignado el comprobante
echo $res['CAEFchVto']; //Fecha de vencimiento del CAE (yyyy-mm-dd)
```
y así obtengo CAE y vencimiento. Pero hay veces en que el pedido de CAE es rechazado y la AFIP devuelve un mensaje como:

`RECHAZADO - Obs: Code=10015 - Combr: 20011 - Msg= Factura B (CbteDesde igual a CbteHasta), DocTipo: 80, DocNro 00000000 no se encuentra registrado en los padrones de AFIP y no corresponde a una cuit p`

Como puedo saber si ocurre esto o en que variable verlo? Para asi no ir siempre directo a res['CAE'] (Que valdría cero o null) y podes guardar esos motivos de rechazo? y no seguir con el proceso de armar la factura cuando no debería?

**Comment by ZombieEater** [comment]
Hola, si es rechazado el CAE vendría vacío, por lo que deberías parsear como dice en la documentación (a partir de la página 11)
[https://www.afip.gob.ar/facturadecreditoelectronica/documentos/manual-desarrollador-COMPG.pdf](https://www.afip.gob.ar/facturadecreditoelectronica/documentos/manual-desarrollador-COMPG.pdf)

Ahi en la respuesta estaría el código de error y en base a ello continuás la ejecución de tu programa en base al error.

**Comment by ZombieEater** [comment]
Hola, si es rechazado el CAE vendría vacío, por lo que deberías parsear como dice en la documentación oficial.

[https://www.afip.gob.ar/ws/documentacion/ws-factura-electronica.asp](https://www.afip.gob.ar/ws/documentacion/ws-factura-electronica.asp)

Ahi en la respuesta estaría el código de error y en base a ello continuás la ejecución de tu programa en base al error.
