### ISSUE TITLE
Attempt to assign property "voucher_number" on array

### ISSUE THREAD

**Issue by dkstudio86** [AfipSDK/afip.php#130]
Versión de PHP 8.1
Versión de Laravel 9.21.4

Al ejecutar la función "CreateNextVoucher", en la línea 135 de ElectronicBilling.php se intenta asignar el valor de voucher number a una propiedad de $res.

`$res->voucher_number	= $voucher_number;`

El problema es que $res es un array y dispara el error del título. La línea debería ser:

`$res['voucher_number']	= $voucher_number;`

**Comment by dkstudio86** [comment]
El problema surge en la versión estable que descarga composer: "0.7.3". En el master está corregido. Quizás sería buena idea generar un nuevo tag.

**Comment by JuanjoArmellino** [comment]
verificado, ha sido un verdadero problema, al dia de hoy , version 0.7.4 continua el problema

**Comment by dkstudio86** [comment]
@JuanjoArmellino hice un fork con la solución y un PR... Pero está pendiente de aprobación. Te paso el link si te sirve del repo con el problema solucionado.
https://github.com/dkstudio86/afip.php
