### ISSUE TITLE
Error Fetching http headers - getPersona_v2

### ISSUE THREAD

**Issue by franvilladaa** [AfipSDK/afip.php#131]
Buenas,

Estoy teniendo un problema en producción. Tengo un sistema que lo único que hace es consultar información de contribuyentes.

El sistema esta en producción hace ya 4/5 meses y hasta hace una semana funcionaba sin problema.

Básicamente hace una semana empecé a obtener un error que decía "Problema para conseguir una conexión a la base", lo extraño es que por momentos funcionaba y después me volvía a tirar eses error. Toda esta semana el sistema funciono re intentando una y otra vez y las consultas iban pasando de a poco. Hoy empecé a obtener un nuevo error que dice: "Error Fetching http headers", y sigue ocurriendo lo mismo no es un error que da todo el tiempo sino que el proceso avanza con ciertas consultas y de repente falla. Lo vuelvo a correr, avanza un poco mas y vuelve a fallar.

Alguno le paso algo similar? O me puede orientar por donde investigar porque me estoy volviendo loco, antes funcionaba todo sin problema y no cambie nada.

Gracias!!

**Comment by Askeshine** [comment]
Hola, pusiste solucionarlo ? estoy con ese proble ahora y no entiendo el porque...

![image](https://user-images.githubusercontent.com/37356127/192122962-7ed36c77-1e90-411f-b02a-f0a6bb3b9d46.png)
