### ISSUE TITLE
Cert y Key sobreescritos al actualizar paquete

### ISSUE THREAD

**Issue by fabianm1705** [AfipSDK/afip.php#132]
Actualicé a la última versión del paquete este fin de semana pero en el proceso perdí mis archivos cert y key ubicados en la carpeta Afip_res, se reemplazaron con archivos en blanco, es un bug o debo tener alguna precaución al actualizar de aquí en adelante? 

Saludos.

**Comment by ivanalemunioz** [comment]
se debe tener precaucion
