### ISSUE TITLE
production.ERROR: Failed to open .../vendor/afipsdk/afip.php/src/Afip_res/cert

### ISSUE THREAD

**Issue by fabianm1705** [AfipSDK/afip.php#133]
Estoy recibiendo este error... Actualicé a la última versión del paquete, mi certificado fue sobreescrito con la nueva versión, voy listando lo hecho y probado:

Reemplazé los archivos cert y key
He dado permisos de escritura a la carpeta Afip_res
A los archivos cert y key les he dado permisos 777
Les he asignado mi usuario, también root y webusers

Pero con ninguno logro que los lea, me sigue saltando este error "failed to open", puede ser que pase algo con la actualización? no sé que pruebas seguir haciendo.

**Comment by ivanalemunioz** [comment]
Reiniciaste el servidor?

**Comment by fabianm1705** [comment]
Si, cada vez, acabo de probar con todas las opciones de usuarios posibles y da el mismo error.

**Comment by fabianm1705** [comment]
Confirmado, hay un problema con la versión 0.7.3 para leer el archivo cert, bajé a la versión 0.7.2 y volvió a conectar sin problemas con afip.
