### ISSUE TITLE
Error SOAP v 0.7.4

### ISSUE THREAD

**Issue by coneman72** [AfipSDK/afip.php#138]
Buenas, actualicé a v0.7.4 y al informar una Nota de Crédito me da un error:

SOAP-ERROR: Encoding: object has no 'Tipo' property in vendor/afipsdk/afip.php/src/Afip.php on line 466

Para mi el problema viene referido a la parte de Comprobantes Asociados.  Estoy enviando en el formato que pide AFIP, es decir algo asi:

"CbtesAsoc":[
{
"CbteAsoc":{
"Tipo":1,
"PtoVta":1,
"Nro":12345,
"Cuit":"xxxxxxxxxxx",
"CbteFch":20220901
}
}
]

**Comment by ivanalemunioz** [comment]
https://github.com/AfipSDK/afip.php/blob/1d9911509dfef8930c0eacc15692fc4e834ea750/examples/CreateVoucher.php#L25 Ahi podes ver un ejemplo de como agregar los comprobantes asociados

**Comment by coneman72** [comment]
Gracias por responder. El formato en el que envío es el correcto y es como lo pide afip pero en la versión 0.7.4 no me funcionó, tuve que volver a la versió 0.6.1 que es la que uso actualmente y ahí anda perfecto. Con 0.6.1 puedo informar sin problemas Facturas, Notas de Crédito, NC Electrónicas, etc con 0.7.4 no, da ese error de SOAP que mencioné arriba. Saludos.
