### ISSUE TITLE
 (10197) Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc

### ISSUE THREAD

**Issue by ebalmaceda** [AfipSDK/afip.php#140]
Hola! No logro hacer un debito, me sale el error:

 (10197) Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc

Intente agregar esos datos al crear el vaucher de esta forma:

'CbteAsoc' => array('Tipo' => $factura_tipo_id, 'PtoVta' => $punto_de_venta, 'Nro' => $factura_numero_float)

donde $factura_tipo_id y $factura_numero_float seria la factura a la que le hago el debito.

Seguramenet estoy haciendo todo mal, les agradesco la ayuda.

**Comment by ivanalemunioz** [comment]
Aqui podes ver la estructua de ejemplo

https://github.com/AfipSDK/afip.php/blob/master/examples/CreateVoucher.php#L25

**Comment by ebalmaceda** [comment]
@ivanalemunioz muchisimas gracias por tu respuesta, en el ejemplo estaba la solucion.
Ya tenia la cabeza quemada y no me rescate de ir al ejemplo oficial.

Aprovecho para felicitarte por el tremendo trabajo que hiciste. Abrazo.
