### ISSUE TITLE
Cómo puedo obtener la condicion frente al IVA?

### ISSUE THREAD

**Issue by fluoroom** [AfipSDK/afip.php#143]
Buenas, para un sistema de facturación en donde trabajo necesito obtener -entre otros- el dato de la condición (Inscripto, Exento, Monotributo). Mi función usa alcance 5 para CUITs y alcance 13 para CUILs. Todo funciona bien, y aprovecho para agradecerles por este gran trabajo de adaptación de SOAP a SDKs en varios lenguajes. 
Ahora bien, no sé cuál es el campo que me especifica la condición de inscripción. Si no hay, podría deducirlo ante la presencia de otros datos, pero no logro sacarle la ficha de qué datos me dan la pista para deducir.
Si alguien acá sabe o se le ocurre cómo hacer, me serviría muchísimo.
Saludos!

**Comment by AfipSDK** [comment]
En el padron alcance 5 te dice los impuestos donde esta inscripto. Si esta
inscripto en monotributo es monotributo, valga la redundancia, y si esta
inscripto en iva es responsable

**Comment by fluoroom** [comment]
Gracias!
Supongo que si existe datosMonotributo lo marco como Mono.
Para diferenciar entre Inscripto y Exento alcanzaría con encontrar algún 'IVA EXENTO' entre los varios impuestos? Y si no lo encuentra se confirma inscripto?

**Comment by ivanalemunioz** [comment]
Desconozco como sale el iva excento

**Comment by fluoroom** [comment]
Pude hacer la deducción de esta forma, capaz a alguien le sirve:

`
$consumidor_final = false;
        $condicion_iva = 'Consumidor final';
        $data = FacturaController::initAfip()->RegisterScopeFive->GetTaxpayerDetails($cuit);
        if (isset($data->errorConstancia)) {
            $data = FacturaController::initAfip()->RegisterScopeThirteen->GetTaxpayerDetails($cuit);
            $consumidor_final = true;
        } else {
            if (isset($data->datosMonotributo)) {
                $condicion_iva = 'Monotributista';
            } else {
                $condicion_iva = 'IVA Inscripto';
                $impuestos = $data->datosRegimenGeneral->impuesto;
                foreach ($impuestos as $impuesto) {
                    if ($impuesto->descripcionImpuesto === "IVA EXENTO") {
                        $condicion_iva = 'IVA Exento';
                        break;
                    }
                }
            }
        }
`
