### ISSUE TITLE
ImpNeto, ImpOpEx, ImpIVA error en los valores

### ISSUE THREAD

**Issue by ebalmaceda** [AfipSDK/afip.php#145]
Estimados, no logro completar correctamente los parametros:
ImpNeto, ImpOpEx, ImpIVA 

Estoy intentando realizar una venta a un cliente con IVA EXCENTO.

seguramente los estoy ingresando mal, 
en ImpNeto pongo el total de la venta sin iva.
en ImpOpEx pongo el total del iva 
en ImpIVA ¿tengo que repetir lo que puse en ImOPEx o como ya lo puse ahi va en 0?

Hay algo mas que me estoy perdiendo??

Les agradesco la ayuda.

**Comment by ivanalemunioz** [comment]
Como te queda armado el $data?

**Comment by ivanalemunioz** [comment]
Proba asi:

```PHP
...
		'ImpTotal' 	=> 121, // Importe total del comprobante
		'ImpTotConc'    => 0,   // Importe neto no gravado
		'ImpNeto' 	=> 0, // Importe neto gravado
		'ImpOpEx' 	=> 121,   // Importe exento de IVA
		'ImpIVA' 	=> 0,  //Importe total de IVA
...
```

Y sacale 
```PHP
...
		'Iva' => $arraysIVAS_corregido, // (Opcional) Alícuotas asociadas al comprobante 	
...
```
