### ISSUE TITLE
Necesita un token para usar el SDK en producction. Ingrese en >> https://app.afipsdk.com << para obtener uno.

### ISSUE THREAD

**Issue by quileab** [AfipSDK/afip.php#146]
Tego entendido que es un proyecto de Código Abierto (licencia MIT) pero tratando de hacer una prueba en "producción" me encuentro con este mensaje.
**Necesita un token para usar el SDK en producction. Ingrese en >> https://app.afipsdk.com << para obtener uno.**
Al ingresar para ver de qué se trata veo que cobran un Dólar por mes?
Es esto así o hay algún error?

**Comment by AfipSDK** [comment]
Es asi, en el enlace podes encontrar los detalles!

**Comment by NRotili** [comment]
Holaaa! Desde cuando pide token? Tenia entendido q la había liberado la library.

**Comment by ivanalemunioz** [comment]
Hace aproximadamente 3 meses
