### ISSUE TITLE
Se puede consultar comprobantes "Recibidos"?

### ISSUE THREAD

**Issue by pcondorip** [AfipSDK/afip.php#148]
Hola buenas, se que con el método GetVoucherInfo se pueden consultar comprobantes, pero estos son solo los que la empresa misma crea ("comprobantes emitidos"), hay alguna manera de consultar los comprobantes generados por terceros ("Comprobantes recibidos" ósea facturas de compras) ? como en la pagina de la afip? gracias

**Comment by ivanalemunioz** [comment]
No el SDK no tiene ningun web service integrado que haga dicha funcionalidad
