### ISSUE TITLE
Fatal error: Uncaught Exception: (600) ValidacionDeToken: Parametro nulo o vacio

### ISSUE THREAD

**Issue by KNC124** [AfipSDK/afip.php#149]
Hola! Estoy intentando probar la libreria y me sale este error.
En la carpeta me fija el XML supuestamente que se logueo.
Alguien sabria?
Gracias de antemano

**Comment by KNC124** [comment]
En la carpeta me fija el XML supuestamente que se logueo => quise decir que el XML se genero

**Comment by ivanalemunioz** [comment]
que se te genero en la carpeta?

**Comment by KNC124** [comment]
Perdon! Me fije nuevamente y tenia problemas con el certificado. Saludos!
