### ISSUE TITLE
El CEE ya posee un TA valido para el acceso al WSN solicitado

### ISSUE THREAD

**Issue by agualefer** [AfipSDK/afip.php#15]
Este error se produce, dependiendo del tráfico en los servidores de AFIP, cuando se intenta obtener ticket de acceso demasiadas veces estando vigente tickets anteriores.

**Comment by AfipSDK** [comment]
Gracias por la contribucion

**Comment by AfipSDK** [comment]
Corresponde a este SDK esa respuesta?

**Comment by agualefer** [comment]
Corregí la entrada. estaba copiado texto de otro SDK. 
Parte del error es este.

> Fatal error: Uncaught Exception: SOAP Fault: ns1:coe.alreadyAuthenticated El CEE ya posee un TA valido para el acceso al WSN solicitado in /Applications/XAMPP/xamppfiles/htdocs/AFIP/Afip.php:230 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Afip.php(171): Afip->CreateServiceTA('wsfe') #1 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php(328): Afip->GetServiceTA('wsfe') #2 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php(304): ElectronicBilling->GetWSInitialRequest('FEParamGetTipos...') #3 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php(182): ElectronicBilling->ExecuteRequest('FEParamGetTipos...') #4 /Applications/XAMPP/xamppfiles/htdocs/AFIP/index.php(15): ElectronicBilling->GetVoucherTypes() #5 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/AFIP/Afip.php on line 230
