### ISSUE TITLE
Warning: openssl_pkcs7_sign(): error getting private key in C:\xampp\htdocs\Sistema\afip\src\Afip.php

### ISSUE THREAD

**Issue by alfsys** [AfipSDK/afip.php#152]
Hola, vi varios hilos sobre esta consulta, aplique alginas de las sugerencias pero no puedo resolver el problema.
Tengo la ultima version de Afip.php, genere un certificado nuevo, esta relacionado correctamente al webservice de facturacion electronica, el cuit lo paso como long, string, etc. lo unico que me llama la atencion es el parametro PASSPHRASE que en el arreglo que se genera despues de la inicializacion de los datos:
 [PRIVATEKEY] => afip/luan/privadaluan102023.key **[PASSPHRASE] => xxxxx** 
por defecto esta xxxxx, que clave va ahi?? la clave fiscal?

desde ya muchas gracias

Alejandro

**Comment by ivanalemunioz** [comment]
Como estas haciendo el new Afip() ?
