### ISSUE TITLE
Sigue vigente esta libreria?

### ISSUE THREAD

**Issue by mluzardi** [AfipSDK/afip.php#153]
Hola esta libreria quedo deprecada? porque no me conecta más, tengo todo correcto, generado los cert, key, autorizado todo, lo venia usando super bien se cayo de un dia para otro y no funciono más, estuve viendo documentación y los nombres de los metodos creo que cambiaron en la nueva versión 

FEParamGetTipos2023-12-16 13:27:49 [181.28.217.29][100][s0t8q0bs9ra31074ha5b71oiv2][error][Exception] **Exception: SOAP Fault: 
HTTP
Could not connect to host**
 in /var/www/clients/client1/web4/web/vendor/afipsdk/afip.php/src/Afip.php:402
Stack trace:
#0 /var/www/clients/client1/web4/web/vendor/afipsdk/afip.php/src/Afip.php(382): AfipWebService->_CheckErrors('FEParamGetTipos...', Object(SoapFault))
#1 /var/www/clients/client1/web4/web/vendor/afipsdk/afip.php/src/Class/ElectronicBilling.php(403): AfipWebService->ExecuteRequest('FEParamGetTipos...', Array)
#2 /var/www/clients/client1/web4/web/vendor/afipsdk/afip.php/src/Class/ElectronicBilling.php(277): ElectronicBilling->ExecuteRequest('FEParamGetTipos...')
#3 /var/www/clients/client1/web4/web/components/AfipService.php(100): ElectronicBilling->GetVoucherTypes()
#4 /var/www/clients/client1/web4/web/views/voucher/_form.php(16): app\components\AfipService->getVoucherTypes()
#5 /var/www/clients/client1/web4/web/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/client...')
#6 /var/www/clients/client1/web4/web/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/client...', '[<span class="s...')

**Comment by ivanalemunioz** [comment]
Que estas ejecutando?

**Comment by mluzardi** [comment]
Ya lo solucione, el tema es que la librería no da error cuando tenes
corriendo la implementacion y te sale solamente q no puede conectar al
host,actualice la misma le puse el nuevo campo token que tampoco lo dice en
instalación y ahora es obligatorio y se soluciono
