### ISSUE TITLE
Errores en TA (Autorizaciones)

### ISSUE THREAD

**Issue by agualefer** [AfipSDK/afip.php#16]
Donde te aparezca este error

> Fatal error: Uncaught Exception: SOAP Fault: ns1:coe.alreadyAuthenticated El CEE ya posee un TA valido para el acceso al WSN solicitado in /Applications/XAMPP/xamppfiles/htdocs/AFIP/Afip.php:230 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Afip.php(171): Afip->CreateServiceTA('wsfe') #1 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php(328): Afip->GetServiceTA('wsfe') #2 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php(304): ElectronicBilling->GetWSInitialRequest('FEParamGetTipos...') #3 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php(182): ElectronicBilling->ExecuteRequest('FEParamGetTipos...') #4 /Applications/XAMPP/xamppfiles/htdocs/AFIP/index.php(15): ElectronicBilling->GetVoucherTypes() #5 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/AFIP/Afip.php on line 230

Es porque en la carpeta AFIP_RES tenemos un archivo llamado "TA-XXXX-wsfe.xml" donde xxx es el CUIT, y esta mal grabado.

La Solucion es eliminar el archivo y reautorizar por  AFIP.

**Comment by AfipSDK** [comment]
Gracias por la contribucion!
