### ISSUE TITLE
RegisterInscriptionProof

### ISSUE THREAD

**Issue by sistemasLang** [AfipSDK/afip.php#160]
Me esta devolviendo al querer buscar la constancia de inscripcion que getPersona_v2 no existe:

SOAP Fault: Client Function ("getPersona_v2") is not a valid method for this service

**Comment by ivanalemunioz** [comment]
Que codigo ejecutas para que te de dicho error?

**Comment by sistemasLang** [comment]
Quiero obtener el registro de inscripcion.
ejecuto la clase: RegisterInscriptionProof.
A la hora de hacer GetTaxpayerDetails si dejo getPersona_v2 me tira error.

**Comment by ivanalemunioz** [comment]
No estoy pudiendo reproducir el error con los pasos que nombras
