### ISSUE TITLE
SOAP Fault: HTTP Could not connect to host

### ISSUE THREAD

**Issue by ebalmaceda** [AfipSDK/afip.php#161]
Hola! Tengo todo correctamente funcionando en un viejo CENTOS 7, estoy mudando exactamente todo igual a un CloudLinux
y cuando intengo enviar una factura mediante el webservice (como lo vengo haciendo hace años) me da el error:

> Uncaught exception 'Exception' with message 'SOAP Fault: HTTP Could not connect to host '

La libreria SOAP de php esta habilitada, es la misma versión de PHP pero claramente algo hay diferente, podrian ayudarme? 
Lo agradesco de antemano.
Gracias!

**Comment by ivanalemunioz** [comment]
Hilo en #5
