### ISSUE TITLE
Client found response content type of 'text/html; charset=iso-8859-1', but expected 'text/xml'.

### ISSUE THREAD

**Issue by ebalmaceda** [AfipSDK/afip.php#162]
Estimados, tengo el problema de certificado vencido, asi lo indica al utilizar el SDK para facturar.
Intengo subir a la web de la afip el archivo CSR para generar el nuevo certificado y me da el siguiente error:
A alguien mas le pasa??
Gracias por la ayuda.

`El Request enviado es inválido. Por favor revíselo.  Client found response content type of 'text/html; charset=iso-8859-1', but expected 'text/xml'.
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at auth2@afip.gov.ar to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
`

**Comment by ivanalemunioz** [comment]
Se ve que hoy hicieron vencer muchos certificados y al intentar crear uno esta dando ese error, segui reintentando aver si te deja crearlo

**Comment by ebalmaceda** [comment]
Tenias razon, acabo de probar hace un rato y pude generarlo, estaba preocupado porque probe todo el día y daba siempre el mismo error.
Muchas gracias por tu laburo!
