### ISSUE TITLE
10016 - El número o fecha del comprobante no se corresponde con el próximo a autorizar. Consultar metodo FECompUltimoAutorizado.

### ISSUE THREAD

**Issue by agualefer** [AfipSDK/afip.php#17]
Este error es uno de los más frecuentes, y suele aparecer en días en que los servidores de AFIP no funcionan correctamente. Básicamente lo que nos indica es que estamos queriendo autorizar un comprobante que no coincide con la numeración que lleva AFIP. Cabe recordar que debemos informar nuestros comprobantes en orden numérico, para cada tipo de comprobante, facturas A, facturas B, etc.

El error se muestra como este:

> Fatal error: Uncaught Exception: (10016) El nÃºmero o fecha del comprobante no se corresponde con el prÃ³ximo a autorizar. Consultar metodo FECompUltimoAutorizado. in /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php:364 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php(308): ElectronicBilling->_CheckErrors('FECAESolicitar', Object(stdClass)) #1 /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php(92): ElectronicBilling->ExecuteRequest('FECAESolicitar', Array) #2 /Applications/XAMPP/xamppfiles/htdocs/AFIP/index.php(42): ElectronicBilling->CreateVoucher(Array) #3 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/AFIP/Class/ElectronicBilling.php on line 364

**Comment by AfipSDK** [comment]
Por lo general este error suele ser de tipeo humano (no ponen el numero o fecha correctas)  quiero aclarar que hasta ahora no me he visto de que a alguien le salga este error por error (valga la redundancia) de los servidores de AFIP.

**Comment by agualefer** [comment]
Pues, esta siendo la prueba con el SCRIPT para Facturar que tenes cargado en el Wiki.

**Comment by agualefer** [comment]
Si, pues, la intencion no es consultar si no generar. y use este molde 

<?php
  date_default_timezone_set('America/Argentina/Buenos_Aires');

include "Afip.php";

$afip = new Afip(
	array(
		
		'CUIT' => "XXXXXX",
		'production' => "false"
	)
);


$data = array(
	'CantReg' 	=> 2,  // Cantidad de comprobantes a registrar
	'PtoVta' 	=> 1,  // Punto de venta
	'CbteTipo' 	=> 6,  // Tipo de comprobante (ver tipos disponibles) 
	'Concepto' 	=> 1,  // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
	'DocTipo' 	=> 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles)
	'DocNro' 	=> 0,  // Número de documento del comprador (0 consumidor final)
	'CbteDesde' 	=> 98983454,  // Número de comprobante o numero del primer comprobante en caso de ser mas de uno
	'CbteHasta' 	=> 98983454,  // Número de comprobante o numero del último comprobante en caso de ser mas de uno
	'CbteFch' 	=> intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
	'ImpTotal' 	=> 121, // Importe total del comprobante
	'ImpTotConc' 	=> 0,   // Importe neto no gravado
	'ImpNeto' 	=> 100, // Importe neto gravado
	'ImpOpEx' 	=> 0,   // Importe exento de IVA
	'ImpIVA' 	=> 21,  //Importe total de IVA
	'ImpTrib' 	=> 0,   //Importe total de tributos
	'MonId' 	=> 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos) 
	'MonCotiz' 	=> 1,     // Cotización de la moneda usada (1 para pesos argentinos)  
	'Iva' 		=> array( // (Opcional) Alícuotas asociadas al comprobante
		array(
			'Id' 		=> 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles) 
			'BaseImp' 	=> 100, // Base imponible
			'Importe' 	=> 21 // Importe 
		)
	), 
);

$res = $afip->ElectronicBilling->CreateVoucher($data);

$res['CAE']; //CAE asignado el comprobante

**Comment by juanledesma** [comment]
Primero tenes que consultar el ultimo comprobante, para saber que numero es en afip, luego le sumas 1 y recién ahí generas el próximo comprobante.

Otra cosa, fíjate la hora del servidor. Yo tuve que cambiar la misma cuando trabaje con php puro.


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: agualefer <notifications@github.com>
Enviado: Sunday, September 30, 2018 3:27:07 PM
Para: AfipSDK/afip.php
Cc: Juan Luis Ledesma; Comment
Asunto: Re: [AfipSDK/afip.php] 10016 - El número o fecha del comprobante no se corresponde con el próximo a autorizar. Consultar metodo FECompUltimoAutorizado. (#17)


Si, pues, la intencion no es consultar si no generar. y use este molde

"XXXXXX", 'production' => "false" ) ); $data = array( 'CantReg' => 2, // Cantidad de comprobantes a registrar 'PtoVta' => 1, // Punto de venta 'CbteTipo' => 6, // Tipo de comprobante (ver tipos disponibles) 'Concepto' => 1, // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios 'DocTipo' => 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles) 'DocNro' => 0, // Número de documento del comprador (0 consumidor final) 'CbteDesde' => 98983454, // Número de comprobante o numero del primer comprobante en caso de ser mas de uno 'CbteHasta' => 98983454, // Número de comprobante o numero del último comprobante en caso de ser mas de uno 'CbteFch' => intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo 'ImpTotal' => 121, // Importe total del comprobante 'ImpTotConc' => 0, // Importe neto no gravado 'ImpNeto' => 100, // Importe neto gravado 'ImpOpEx' => 0, // Importe exento de IVA 'ImpIVA' => 21, //Importe total de IVA 'ImpTrib' => 0, //Importe total de tributos 'MonId' => 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos) 'MonCotiz' => 1, // Cotización de la moneda usada (1 para pesos argentinos) 'Iva' => array( // (Opcional) Alícuotas asociadas al comprobante array( 'Id' => 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles) 'BaseImp' => 100, // Base imponible 'Importe' => 21 // Importe ) ), ); $res = $afip->ElectronicBilling->CreateVoucher($data); $res['CAE']; //CAE asignado el comprobante

**Comment by agualefer** [comment]
mmmmm... ese detalle no lo vi mencionado, esta bueno saberlo. Respecto del servidor tengo especificada la hora y fecha con esta linea :

`date_default_timezone_set('America/Argentina/Buenos_Aires');`

Con eso es suficiente, voy a ver lo que mencionas y si no los molesto....

**Comment by juanledesma** [comment]
Lo de la hora esta bien.

Proba que seguro funciona… estoy probando la librería hace rato y anda bien, todavía no la saque en producción.

Tengo un tema con la generación del PDF.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: agualefer <notifications@github.com>
Enviado: Sunday, September 30, 2018 3:37:58 PM
Para: AfipSDK/afip.php
Cc: Juan Luis Ledesma; Comment
Asunto: Re: [AfipSDK/afip.php] 10016 - El número o fecha del comprobante no se corresponde con el próximo a autorizar. Consultar metodo FECompUltimoAutorizado. (#17)


mmmmm... ese detalle no lo vi mencionado, esta bueno saberlo. Respecto del servidor tengo especificada la hora y fecha con esta linea :

date_default_timezone_set('America/Argentina/Buenos_Aires');

Con eso es suficiente, voy a ver lo que mencionas y si no los molesto....

**Comment by agualefer** [comment]
Ahora si!

El codigo quedaria asi:

`
//Devuelve el número del último comprobante creado para el punto de venta 1 y el tipo de comprobante 6 (Factura B)

$last_voucher = $afip->ElectronicBilling->GetLastVoucher(1,6);

echo $last_voucher;
$valfac = $last_voucher + 1;

echo "<br>";

$data = array(
	'CantReg' 	=> 2,  // Cantidad de comprobantes a registrar
	'PtoVta' 	=> 1,  // Punto de venta
	'CbteTipo' 	=> 6,  // Tipo de comprobante (ver tipos disponibles) 
	'Concepto' 	=> 1,  // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
	'DocTipo' 	=> 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles)
	'DocNro' 	=> 0,  // Número de documento del comprador (0 consumidor final)
	'CbteDesde' 	=> $valfac,  // Número de comprobante o numero del primer comprobante en caso de ser mas de uno
	'CbteHasta' 	=> $valfac,  // Número de comprobante o numero del último comprobante en caso de ser mas de uno
	'CbteFch' 	=> intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
	'ImpTotal' 	=> 121, // Importe total del comprobante
	'ImpTotConc' 	=> 0,   // Importe neto no gravado
	'ImpNeto' 	=> 100, // Importe neto gravado
	'ImpOpEx' 	=> 0,   // Importe exento de IVA
	'ImpIVA' 	=> 21,  //Importe total de IVA
	'ImpTrib' 	=> 0,   //Importe total de tributos
	'MonId' 	=> 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos) 
	'MonCotiz' 	=> 1,     // Cotización de la moneda usada (1 para pesos argentinos)  
	'Iva' 		=> array( // (Opcional) Alícuotas asociadas al comprobante
		array(
			'Id' 		=> 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles) 
			'BaseImp' 	=> 100, // Base imponible
			'Importe' 	=> 21 // Importe 
		)
	), 
);

$res = $afip->ElectronicBilling->CreateVoucher($data);

echo $res['CAE']; //CAE asignado el comprobante`

estas cosas tendrian que estar son de mucha ayuda....

te hago una consulta, aprovechando el caso.

En tema de CAE, CAI Y Fechas de vencimiento, se que se pueden obtener desde la api y creo haberlo visto. 

Pero, existe alguna seccion en la pagina de AFIP que se guarde esto? / 

Caso contrario supongo que con  `$last_voucher = $afip->ElectronicBilling->GetLastVoucher(1,6); ` lo obtendre en serie, digamos, de corrido... o existe  alguna manera de reobtenerlo?

**Comment by juanledesma** [comment]
la forma mas segura de obtenerlo es consultando el ultimo comprobante, como esta en el código de abajo.

Después esta info la tenes que guardar en la base de datos, o no se que tipo de software estas haciendo. Y consultar ese comprobante en concreto. Pero no recomiendo utilizar otro método.

Te consulto, quizás podes darme una mano. Como tenes pensado generar el PDF?


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: agualefer <notifications@github.com>
Enviado: Sunday, September 30, 2018 3:44:07 PM
Para: AfipSDK/afip.php
Cc: Juan Luis Ledesma; Comment
Asunto: Re: [AfipSDK/afip.php] 10016 - El número o fecha del comprobante no se corresponde con el próximo a autorizar. Consultar metodo FECompUltimoAutorizado. (#17)


Ahora si!

El codigo quedaria asi:

`
//Devuelve el número del último comprobante creado para el punto de venta 1 y el tipo de comprobante 6 (Factura B)

$last_voucher = $afip->ElectronicBilling->GetLastVoucher(1,6);

echo $last_voucher;
$valfac = $last_voucher + 1;

echo "
";

$data = array(
'CantReg' => 2, // Cantidad de comprobantes a registrar
'PtoVta' => 1, // Punto de venta
'CbteTipo' => 6, // Tipo de comprobante (ver tipos disponibles)
'Concepto' => 1, // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
'DocTipo' => 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles)
'DocNro' => 0, // Número de documento del comprador (0 consumidor final)
'CbteDesde' => $valfac, // Número de comprobante o numero del primer comprobante en caso de ser mas de uno
'CbteHasta' => $valfac, // Número de comprobante o numero del último comprobante en caso de ser mas de uno
'CbteFch' => intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
'ImpTotal' => 121, // Importe total del comprobante
'ImpTotConc' => 0, // Importe neto no gravado
'ImpNeto' => 100, // Importe neto gravado
'ImpOpEx' => 0, // Importe exento de IVA
'ImpIVA' => 21, //Importe total de IVA
'ImpTrib' => 0, //Importe total de tributos
'MonId' => 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos)
'MonCotiz' => 1, // Cotización de la moneda usada (1 para pesos argentinos)
'Iva' => array( // (Opcional) Alícuotas asociadas al comprobante
array(
'Id' => 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles)
'BaseImp' => 100, // Base imponible
'Importe' => 21 // Importe
)
),
);

$res = $afip->ElectronicBilling->CreateVoucher($data);

echo $res['CAE']; //CAE asignado el comprobante`

estas cosas tendrian que estar son de mucha ayuda....

te hago una consulta, aprovechando el caso.

En tema de CAE, CAI Y Fechas de vencimiento, se que se pueden obtener desde la api y creo haberlo visto.

Pero, existe alguna seccion en la pagina de AFIP que se guarde esto? /

Caso contrario supongo que con $last_voucher = $afip->ElectronicBilling->GetLastVoucher(1,6); lo obtendre en serie, digamos, de corrido... o existe alguna manera de reobtenerlo?

**Comment by agualefer** [comment]
Porsupuesto. Te Ayudo. 

Pero al pasarlo a PDF podes Hacerlo con esta utilidad. http://www.fpdf.org/, esta genial y en espa;ol. 

En lo particular, podes generar el documento en HTML con bootstrap a mi personalmente me gusta el esquema de factura que tiene American Express. Ellos tienen dos cuerpos en el mismo documento, (hablando en Bootstrap seria asi), col-md-9 y col-md-3. Donde md-3 es el apartado donde se mostraria los datos de la factura, fecha de vencimiento, y demas datos. en el md-9 tenes en la cabecera los datos del lugar, y hacia abajo el resumen de la compra o de la factura en fin. 

Y si estas en un PC guardarlo como PDF desde el navegador.

Al mandarlo por mail podes hacer que acceda a un link y que lo vea, Al hacer un PDF estas obligado a guardar el archivo en el server o despacharlo por Mail.... y eso genera transferencia...

**Comment by juanledesma** [comment]
Voy a probar , estaba probando con jasper report , pero tarda en generar el PDF, unos pocos segundos pero es molesto. Después tengo dos opciones que ya las probe. Una es enviarlo por mail y la otra imprimirlo sin abrir el PDF. Depende de la configuración del sistema hace una, la otra o ambas.

Gracias.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: agualefer <notifications@github.com>
Enviado: Sunday, September 30, 2018 3:59:37 PM
Para: AfipSDK/afip.php
Cc: Juan Luis Ledesma; Comment
Asunto: Re: [AfipSDK/afip.php] 10016 - El número o fecha del comprobante no se corresponde con el próximo a autorizar. Consultar metodo FECompUltimoAutorizado. (#17)


Porsupuesto. Te Ayudo.

Pero al pasarlo a PDF podes Hacerlo con esta utilidad. http://www.fpdf.org/, esta genial y en espa;ol.

En lo particular, podes generar el documento en HTML con bootstrap a mi personalmente me gusta el esquema de factura que tiene American Express. Ellos tienen dos cuerpos en el mismo documento, (hablando en Bootstrap seria asi), col-md-9 y col-md-3. Donde md-3 es el apartado donde se mostraria los datos de la factura, fecha de vencimiento, y demas datos. en el md-9 tenes en la cabecera los datos del lugar, y hacia abajo el resumen de la compra o de la factura en fin.

Y si estas en un PC guardarlo como PDF desde el navegador.

Al mandarlo por mail podes hacer que acceda a un link y que lo vea, Al hacer un PDF estas obligado a guardar el archivo en el server o despacharlo por Mail.... y eso genera transferencia...

**Comment by agualefer** [comment]
Yo en lo particular uso Facturante para realizar las facturas y no solo me copio el PDF que generan a mi servidor si no que ellos lo envian automaticamente. YO, prefiero tener copia en ese caso. ahora si lo vas a guardar en la Base de datos y queres evitar un riesgo de seguridad por un acceso a la base ... con una consulta basica como un get en url... genera el pdf y envialo por mail...

mi humilde opinion

**Comment by AfipSDK** [comment]
El voucher_number te lo genera automaticamente cuando usas CreateNextVoucher en caso de que uses CreateVoucher es equivalente el numero que le pasas en 'CbteDesde' => $valfac

**Comment by agualefer** [comment]
Claro, no me explique bien.
Mi cuestión esta en que quiero obtener el comprobante completo. XXXX-XXXXXXX donde obviamente los primeros 4 numero son el punto de venta... esto, saben como asociarlo a los puntos de venta que ya se tienen registrados en facturación electronica?

**Comment by agualefer** [comment]
> Claro, no me explique bien.
> Mi cuestión esta en que quiero obtener el comprobante completo. XXXX-XXXXXXX donde obviamente los primeros 4 numero son el punto de venta... esto, saben como asociarlo a los puntos de venta que ya se tienen registrados en facturación electronica?

La respuesta esta en 

```
 $data = array(
        
        'CantReg'   => 1,  // Cantidad de comprobantes a registrar
        **'PtoVta'  =>** 1,  // Punto de venta
```

**Comment by informaticaquemu** [comment]
Hola! pudiste resolver lo del fpdf y los números de factura?

**Comment by matiasslatina** [comment]
Hola, quería consultarles como generan el código de barras para la factura.

**Comment by guillebalmacedaonline** [comment]
Buenas señores el codigo de barras se conforma con la siguiente estructura:
CUIT+TIPOCOMPROBANTE+PUNTOVENTA+CAE+FECHAVENCIMIENTOCAE+NUMERO VERIFICADOR

`$cuit = str_replace("-","",$conf_fe->cuit);
      $tipoCompro = str_pad($venta->tipo_venta, 2, "0", STR_PAD_LEFT);
      $puntoVenta = str_pad(1, 4, "0", STR_PAD_LEFT);
      $cae = $venta->CAE;
      $fechaVtoCae = str_replace("-","",$venta->CAEFchVto);
      $codigo = $cuit.$tipoCompro.$puntoVenta.$cae.$fechaVtoCae;
      $codigoBar = $this->verificadorBase10($codigo);`

El numero verificador se saca con el siguiente calculo. Paso funcion:

`    private function verificadorBase10($codigo){
        $splitCodigo = str_split($codigo);
        $bandera = true;
        $sumaPar  = 0;
        $sumaImpar  = 0;
        foreach ($splitCodigo as $value) {
            switch ($bandera) {
                case true:
                    $sumaImpar += $value;
                    $bandera = false;
                    break;
                case false:
                    $sumaPar += $value;
                    $bandera = true;
                    break;
            }
        }
        $etapa2 = $sumaImpar * 3;
        $etapa4 = $etapa2 + $sumaPar;

        $res = ($etapa4 % 10);
        if($res == 0){
            $codigoFinal = 0;
            $cadenaFinal = ''.$codigo.$codigoFinal.'';

        }
        if($res != 0){
            $codigoFinal = 10 - $res;
            $cadenaFinal = ''.$codigo.$codigoFinal.'';
        }

        return $cadenaFinal;
    }`

Espero que sea util, cualquier consulta. A Disposición, saludos.

**Comment by matiasslatina** [comment]
Muchísimas gracias @guillebalmacedaonline !!!
