### ISSUE TITLE
Error al generar una factura, "(10016) El número o fecha del comprobante no se corresponde con el próximo a autorizar. Consultar metodo FECompUltimoAutorizado."

### ISSUE THREAD

**Issue by juancarlosDH** [AfipSDK/afip.php#20]
Buenas amigo, probe e instalé la libreria, con respecto a la consulta del padron funciona perfecto, tengo es inconvenientes con la factura Electronica (ElectronicaBilling) en especial con el método CreateVoucher, te detallo lo que hice:

//creé la variables para la conexion
$options = [
            'CUIT' => XXXXXXXXX,
            'res_folder' => '',
            'ta_folder' => 'xmlgenerados',
            'cert' => 'claves/XXXXXXXXX/cwcert.crt',
            'key' => 'claves/XXXXXXXXX/cwkey.key',
            'production' => false,
        ];

        $afip = new Afip($options);

        $last_voucher = $afip->ElectronicBilling->GetLastVoucher(1,6);
//este ultimo metodo funciona perfecto y me retorna el ultimo recibo.

//pruebo con los mismos datos de tu ejemplo:
        $data = array(
        	'CantReg' 	=> 1,  // Cantidad de comprobantes a registrar
        	'PtoVta' 	=> 1,  // Punto de venta
        	'CbteTipo' 	=> 6,  // Tipo de comprobante (ver tipos disponibles)
        	'Concepto' 	=> 1,  // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
        	'DocTipo' 	=> 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles)
        	'DocNro' 	=> 0,  // Número de documento del comprador (0 consumidor final)
        	'CbteDesde' 	=> $last_voucher,  // Número de comprobante o numero del primer comprobante en caso de ser mas de uno
        	'CbteHasta' 	=> $last_voucher,  // Número de comprobante o numero del último comprobante en caso de ser mas de uno
        	'CbteFch' 	=> intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
        	'ImpTotal' 	=> 121, // Importe total del comprobante
        	'ImpTotConc' 	=> 0,   // Importe neto no gravado
        	'ImpNeto' 	=> 100, // Importe neto gravado
        	'ImpOpEx' 	=> 0,   // Importe exento de IVA
        	'ImpIVA' 	=> 21,  //Importe total de IVA
        	'ImpTrib' 	=> 0,   //Importe total de tributos
        	'MonId' 	=> 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos)
        	'MonCotiz' 	=> 1,     // Cotización de la moneda usada (1 para pesos argentinos)
        	'Iva' 		=> array( // (Opcional) Alícuotas asociadas al comprobante
        		array(
        			'Id' 		=> 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles)
        			'BaseImp' 	=> 100, // Base imponible
        			'Importe' 	=> 21 // Importe
        		)
        	),
        );

        
        $res = $afip->ElectronicBilling->CreateVoucher($data);
        //aqui es donde da el error:
            //"(10016) El número o fecha del comprobante no se corresponde con el próximo a autorizar. Consultar metodo FECompUltimoAutorizado."

Tengo algun error yo?

Gracias de antemano.

**Comment by AfipSDK** [comment]
Lo solucionaste poniendo +1 ?

**Comment by guillebalmacedaonline** [comment]
El procedimiento correcto seria obtener el ultimo comprobante a generar y
sumar 1. Siempre hay que pasar el proximo numero de comprobante.

**Comment by agualefer** [comment]
```
    $last_voucher = $afip->ElectronicBilling->GetLastVoucher($configdb['afippuntodeventa'],11);

    $valfac = $last_voucher + 1;
```

**Comment by agualefer** [comment]
Aca se explica
[](https://github.com/AfipSDK/afip.php/issues/17)
