### ISSUE TITLE
Corrección al método CreateNextVoucher de la clase ElectronicBilling

### ISSUE THREAD

**Issue by juancarlosDH** [AfipSDK/afip.php#21]
Buenas noches, probé generar el siguiente recibo usando tu libreria usando:

$options = [
            'CUIT' => XXXXXXXXXXX,
            'res_folder' => 'ruta',
            'ta_folder' => 'ruta/xmlgenerados',
            'cert' => 'claves/XXXXXXXXXXX/cwcert.crt',
            'key' => 'claves/XXXXXXXXXXX/cwkey.key',
            'production' => false,
        ];

        $afip = new Afip($options);

        $data = array(
        	'CantReg' 	=> 1,  // Cantidad de comprobantes a registrar
        	'PtoVta' 	=> 1,  // Punto de venta
        	'CbteTipo' 	=> 6,  // Tipo de comprobante (ver tipos disponibles)
        	'Concepto' 	=> 1,  // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
        	'DocTipo' 	=> 99, // Tipo de documento del comprador (99 consumidor final, ver tipos disponibles)
        	'DocNro' 	=> 0,  // Número de documento del comprador (0 consumidor final)
        	'CbteDesde' => 1,  // Número de comprobante o numero del primer comprobante en caso de ser mas de uno
        	'CbteHasta' => 1,  // Número de comprobante o numero del último comprobante en caso de ser mas de uno
        	'CbteFch' 	=> intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
        	'ImpTotal' 	=> 121, // Importe total del comprobante
        	'ImpTotConc' 	=> 0,   // Importe neto no gravado
        	'ImpNeto' 	=> 100, // Importe neto gravado
        	'ImpOpEx' 	=> 0,   // Importe exento de IVA
        	'ImpIVA' 	=> 21,  //Importe total de IVA
        	'ImpTrib' 	=> 0,   //Importe total de tributos
        	'MonId' 	=> 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos)
        	'MonCotiz' 	=> 1,     // Cotización de la moneda usada (1 para pesos argentinos)
        	'Iva' 		=> array( // (Opcional) Alícuotas asociadas al comprobante
        		array(
        			'Id' 		=> 5, // Id del tipo de IVA (5 para 21%)(ver tipos disponibles)
        			'BaseImp' 	=> 100, // Base imponible
        			'Importe' 	=> 21 // Importe
        		)
        	),
        );

        $res = $afip->ElectronicBilling->CreateNextVoucher($data);

//Da el siguiente error:
Class : ElectronicBilling lline: 134
message: "Cannot use object of type stdClass as array"

Esa linea tiene lo siguiente:
$res['voucher_number'] 	= $voucher_number;

Lo cambié a:
$res->voucher_number 	= $voucher_number;

Y funcionó perfecto, generó el CAE y los demás datos.

Espero sea de utilidad.

Saludos.

**Comment by AfipSDK** [comment]
Que extraño no habia escuchado que alguien tuviera problemas con eso, gracias por mencionarlo, que version de php usas?

**Comment by agualefer** [comment]
estas programando orientado a objetos?

**Comment by juancarlosDH** [comment]
Lo estoy usando con Laravel 5.5 y php 7.1

**Comment by hugomonaco** [comment]
Hola, estoy teniendo este mismo problema con Laravel 8.0 y PHP 7.3. Probe la solucion de @juancarlosDH y anda perfecto.
Hay alguna otroa forma de solucionarlo?. Claro que podria hacer un fork del repo y modificarlo, pero me intenteresa mantener la dependencia via composer al repo original.

**Comment by hugomonaco** [comment]
Muchas gracias por el fix
