### ISSUE TITLE
Observaciones afip 

### ISSUE THREAD

**Issue by juanledesma** [AfipSDK/afip.php#22]
Buenas noches, consulta.

Como puedo saber si afip observó el comprobante.? Ya que viendo la información del voucher ese campo no se encuentra.

Puede ser que esté figure solo cuando el comprobante tenga una observación.?

Saludos.

**Comment by AfipSDK** [comment]
Hola Juan, podes hacer esta preguta en el foro https://groups.google.com/forum/#!forum/afip-php
