### ISSUE TITLE
 afip.php/src/Class/ElectronicBilling.php

### ISSUE THREAD

**Issue by gonzakpo** [AfipSDK/afip.php#23]
Linea 287:
	public function FormatDate($date)
	{
		return date_format(DateTime::CreateFromFormat('Ymd', $date.''), 'Y-m-d');
	}

Pasar de un string a un datetime y devuelta a string, creo que seria mejor devolver el valor original del web service como dice la documentacion:
CAEFchVto String(8)

**Comment by gonzakpo** [comment]
Entiendo pero es muy específica la conversión y como te digo es pasar a objeto y devuelta a string. Yo devolvería como viene y que cada uno haga como mejor le parezca luego

**Comment by AfipSDK** [comment]
Si lo queres como viene basta con no usar ese metodo

**Comment by gonzakpo** [comment]
Claro.
public function CreateVoucher($data, true)
Eso seria pasando la opcion true como segundo parametro?

**Comment by AfipSDK** [comment]
Este metodo no se usa, es para aquellos que quieran convertir la fecha que
viene por defecto en los web services (yyyymmdd) a una con los guiones
yyyy-mm-dd, no se usa automáticamente dentro de la libreria, por ningun
metodo, si no lo necesitas simplemente no escribis ningun cosigo que lo
incluya

**Comment by gonzakpo** [comment]
https://github.com/AfipSDK/afip.php/blob/master/src/Class/ElectronicBilling.php
Linea 100 lo utiliza

**Comment by AfipSDK** [comment]
Tenes razon!! Jajaja (perdon uno se olvida de cosas) Es porque la idea del SDK es facilitar las cosas desde el principio, y una fecha mas legible es mas utilizada que una que tangan que transformar uno mismo si o si

**Comment by gonzakpo** [comment]
jaja claro bueno quizas utilizo el parametro true para que devuelta todos los valores y lo parseo. Gracias
