### ISSUE TITLE
Consulta sobre la estructura del código

### ISSUE THREAD

**Issue by choma** [AfipSDK/afip.php#24]
Estoy probando la librería, en particular la facturación electrónica, y veo que funciona muy bien.

Pero me surgen algunas dudas respecto de la forma en que está estructurado el código:

- Las clases no tienen namespace, hay alguna razón por la que decidiste hacerlo de esta forma?
- Veo que [se usa include](https://github.com/AfipSDK/afip.php/blob/2679827f798c8313bf2675d0d1c67c0300d0d694/src/Afip.php#L250), en lugar de un autoloader. Si hay alguna razón para no usar un autoloader, al menos se podría usar `include_once()`, para evitar un error que se produce si se unsetean las properties de la clase.

**Comment by AfipSDK** [comment]
No, ninguna razon en particular para hacerlo de esa forma.
Porque se unsetearian las propiedades?
