### ISSUE TITLE
Implementación del webservice wmtxca

### ISSUE THREAD

**Issue by choma** [AfipSDK/afip.php#25]
Estoy interesado en implementar el webservice wsmtxca (para facturas A y B con detalle de items).. [Aquí la documentación](http://www.afip.gob.ar/fe/documentos/WebServiceMTXCAv08.pdf).
Comencé con algunas pruebas, pero quisiera saber si alguien más está trabajando en esto y tiene algún avance.

**Comment by choma** [comment]
Hice un [fork](https://github.com/choma/afip.php/) en el que comencé con las pruebas.

Copié e intenté respetar el enfoque de la clase ElectronicBilling. Tengo un par de commits con una primera (y muy verde) implementación de algunas de las operaciones del webservice. A saber (según listado del punto 2.4.1 de la documentación del webservice):
* Para CAE
  * [x] consultarPuntosVentaCAE
  * [x] autorizarComprobante
* Para CAEA
  * [x] consultarCAEAEntreFechas
  * [x] consultarCAEA
  * [x] consultarPtosVtaCAEANoInformados
  * [x] consultarPuntosVentaCAEA
  * [ ] informarAjusteIVACAEA
  * [ ] informarAjusteIVACAEA
  * [ ] informarCAEANoUtilizadoPtoVta
  * [ ] informarCAEANoUtilizado
  * [x] solicitarCAEA
* Para ambos
  * [x] autorizarAjusteIVA
  * [x] consultarAlicuotasIVA
  * [x] consultarComprobante
  * [x] consultarCondicionesIVA
  * [x] consultarCotizacionMoneda
  * [x] consultarMonedas
  * [x] consultarPuntosVenta
  * [x] consultarTiposComprobante
  * [x] consultarTiposDatosAdicionales
  * [x] consultarTiposDocumento
  * [x] consultarTiposTributo
  * [x] consultarUltimoComprobanteAutorizado
  * [x] consultarUnidadesMedida
  * [x] dummy

Todavía tengo que implementar algunas operaciones de CAEA, pero me trabé con una en particular `InformarCAEANoUtilizado`, que me da un error por no tener un punto de venta habilitado al parecer.
Además, habrá que revisar el nombre de la clase y de los métodos.

Voy a seguir avanzando. Quienes puedan, por favor, revisen, prueben y critiquen/comenten.

**Comment by gonzakpo** [comment]
Cual aseria la mejora de utilizar dicho web service?

**Comment by choma** [comment]
@gonzakpo, los principales webservices de facturación son:
* **WSFEV1:** para comprobantes A, B y C **sin detalle de item**,
* **WSMTXCA:** para comprobantes A y B **con detalle items**

[Hay algunos otros](http://www.afip.gob.ar/ws/documentacion/ws-factura-electronica.asp) para usos más específicos.

**Comment by choma** [comment]
@odv144, la afip no obliga a usar uno u otro webservice, eso lo elegís vos dependiendo de las necesidades de tu cliente.
Lo que no creo que puedas hacer es consignar en la factura impresa información distinta de la que le envias a la afip vía webservice. De todas formas son detalles que no tengo muy claros, y que en todo caso habría que consultar con algún contador.

**Comment by harlyman** [comment]
Hola @choma, con el fork que creaste es posible crear una factura con detalle de lo facturado??, lo necesito y con urgencia y hace meses que tenia todo listo para usar el AfipSDK, y recien me desayuno que no puedo crear facturas con items, por eso la urgencia

**Comment by choma** [comment]
@harlyman, el fork era para eso, ya que implementa el webservice de facturación con detalle de AFIP, pero no está ni cerca de ser usable en producción. Tendrías que completar los endpoints que faltan y, sobre todo, probar a fondo.

**Comment by alegalicia** [comment]
una consulta como agrego mi key y crt al aplicativo?

**Comment by ivanalemunioz** [comment]
@alegalicia aquí dice https://github.com/AfipSDK/afip.php/wiki/Primeros-pasos#importante

**Comment by alegalicia** [comment]
Gracias me funciono bien, por que puede ser que el padrón 10 y 13 me regrese en blanco siendo que existe el CUIT, estoy haciendo uso del servicio del AFIP de homologacion para test.
me puedes ayudar porfa.
gracias

**Comment by alegalicia** [comment]
Buenas tardes ivan disculpa que te moleste, te quería consultar si hay alguna manera de solo recuperar el token sign para poder realizar los otros modulos, como de débito o los demás.- 

agradecería tu ayuda.-

**Comment by ivanalemunioz** [comment]
@alegalicia este no es el lugar correcto para hablar de estos temas, se termina ensuciando el hilo con info irrelevante, por favor utiliza el foro, abri una issue nueva o envíanos un correo a afipsdk@gmail.com
