### ISSUE TITLE
Directorio de cert y key fuera de la carpeta de API

### ISSUE THREAD

**Issue by agualefer** [AfipSDK/afip.php#26]
Buenas! se que muchos usuarios ya preguntaron esto, pero la verdad es que en este caso lo estoy intentando ya que tengo el caso de un cliente con mas de una data fiscal. y este metodo me facilita unas cuestiones.
la idea es que tome los Cert & Key en este directorio ../../../files/private/afip/

El Codigo seria:
`  $afip = new Afip( 
    array( 
      'CUIT' => $afipdb['cuit'],  
      'production' => true,
      'res_folder' => '../../../files/private/afip/',
      'key' => $afipdb['llave'],
      'cert' => $afipdb['certificado']
    ) 
  );`

Pero me da el siguiente error

`Fatal error: Uncaught Exception: Failed to open ../../../files/private/afip/f27d03ca21ff28095a21ab7e29435041.cert in /home/xxx/public_html/ventas/core/source/afip.core/Afip.php:139 Stack trace: #0 /home/xxx/public_html/ventas/core/framework/notadeventa/post.afip.crearfactura.php(38): Afip->__construct(Array) #1 {main} thrown in /home/xxx/public_html/ventas/core/source/afip.core/Afip.php on line 139`

Como puedo solucionarlo?

**Comment by AfipSDK** [comment]
Puedes preguntarlo en el foro https://groups.google.com/forum/#!forum/afip-php
