### ISSUE TITLE
El campo 'Importe Total' ImpTotal, debe ser igual a la suma de ImpTotConc + ImpNeto + ImpOpEx + ImpTrib + ImpIVA.

### ISSUE THREAD

**Issue by lfvergara** [AfipSDK/afip.php#27]
Buenas noches! Podrían ayudarme con el siguiente error:
**El campo 'Importe Total' ImpTotal, debe ser igual a la suma de ImpTotConc + ImpNeto + ImpOpEx + ImpTrib + ImpIVA.'**

Pero los valores me dan iguales, ademas ha llegado a autorizarme con diferencias de un centavo y ha no autorizarme lo que me da igual.
Por favor algo de ayuda!
Muchas gracias de antemano!

**Comment by AfipSDK** [comment]
Puedes preguntarlo en el [foro de la libreria ](https://groups.google.com/forum/#!forum/afip-php)
