### ISSUE TITLE
 'Exception' with message '(10015) 

### ISSUE THREAD

**Issue by gustavosp** [AfipSDK/afip.php#29]
Hola
 Se me presento el siguiente error, pasando "'DocNro' =>$_GET['DocNro'],"  con valor 20111111112, 

_( ! ) Fatal error: Uncaught exception 'Exception' with message '(10015) Factura B (CbteDesde igual a CbteHasta), DocTipo: 80, DocNro 2147483647 no se encuentra registrado en los padrones de AFIP y no corresponde a una cuit pais.' in C:\utiles\wamp\www\afip\src\Class\ElectronicBilling.php on line 364_

Como que en algun lugar se convierte a  2147483647, como dice el error.

Por lo pronto lo solucione  cambiando en _wsfe.wsdl_  la linea 53 x
    `  <s:element minOccurs="1" maxOccurs="1" name="DocNro" type="s:string"/>`

**Comment by AfipSDK** [comment]
Debes usar una version de 64bits de php, para mas ayuda pregunta en el [foro de la libreria](https://groups.google.com/forum/#!forum/afip-php)
