### ISSUE TITLE
Manejo de errores

### ISSUE THREAD

**Issue by arieltallerpd** [AfipSDK/afip.php#32]
Hola, mi consulta es ¿como manejar los errores?. Supongamos que CreateVoucher() arroja un error por X motivo y quiero frenar la ejecución o poner una condición. Que arroja CreateVoucher() cuando no se pudo crear un comprobante?. Gracias

**Comment by agustinbus** [comment]
Como estas, yo tenia el mismo problema y lo resolví de una forma que no se si es la mejor. Modifique un poco el metodo _CheckErrors de la clase ElectronicBilling, para que, en lugar de arrojar una excepción, retorne el array de errores. Además hay que modificar cada metodo de ElectronicBilling para que funcione correctamente.

Saludos!

**Comment by dyhsoluciones** [comment]
Me recontra interesa el tema, porque, por ejemplo si el comprador da un cuit incorrecto me sale un error fatal y no puedo volver a la pagina para coregir.

**Comment by dyhsoluciones** [comment]
Hoy estuve probando, te paso la solucion, con un try and catch funciona perfecto:
		try {
		    $res = $afip->ElectronicBilling->CreateVoucher($data);
		}
		catch (Exception $e)
		{
			//Aca guardo el error que se genero...
		    $excepcion_capturada =  $e->getMessage();			
			
//Pongo esta alerta para que no se siga ejecutando otras cosas y poder mostrar el mensaje anterior mas lindo jajaja
			$alerta = true;						
		}

**Comment by arieltallerpd** [comment]
> Hoy estuve probando, te paso la solucion, con un try and catch funciona perfecto:
> try {
> $res = $afip->ElectronicBilling->CreateVoucher($data);
> }
> catch (Exception $e)
> {
> //Aca guardo el error que se genero...
> $excepcion_capturada = $e->getMessage();
> 
> //Pongo esta alerta para que no se siga ejecutando otras cosas y poder mostrar el mensaje anterior mas lindo jajaja
> $alerta = true;
> }

Muchas gracias dyhsoluciones. Estaba buscando algo así de simple, no se me había ocurrido solo buscaba atrapar el error y frenar la ejecución (try/catch) Genial!

**Comment by piperarcher** [comment]
Buenas! Hay alguna forma de averiguar si un número de documento existe en el padrón de AFIP para poder emitirle la factura?
