### ISSUE TITLE
Computador no Autorizado, es necesario el pkcs12 en php?

### ISSUE THREAD

**Issue by NicoMachado** [AfipSDK/afip.php#35]
Buenos Dias,
desarrolle la implementacion de FCE en php con xampp. 

Funciono perfecto, en homologacion, en mi maquina y en la del cliente.
Pero cambie a produccion, ajustando los parametros necesarios.

hice todos los pasos  segun el pdf de la Afip (WSAA.ObtenerCertificado.pdf)
Ahora bien, obtiene el TA, pero no puedo consumir ningun webservice ...
es solo por un tema de relaciones ? ( me estoy peleando con el contador) o es importante generar ese ultimo paso de generar el pkcs12  ?
Yo tenia entendido que no importa la maquina.

La aplicación corre en un windows 7/32bits...
A futuro correra en un hosting.

Gracias!
PD: Esto es mas una consulta que un issue!
PD 2: esta libreria ya deberia ser Version 1.0 !

**Comment by ctorres90** [comment]
Buenas, para solucionarlo tenes que hacer lo siguiente.
1 – Entrar a la página de AFIP: www.afip.gov.ar e ingresar con CUIT y clave fiscal.
2 – Ir a “Administracion de Relaciones de Clave Fiscal”
3 – Seleccionar la empresa/representado
4 – Ir a Nueva Relación
5 – Seleccionar el menú de AFIP > Webservices > Facturación Electrónica.
6 – Seleccionar el Alias y confirmar.

**Comment by AfipSDK** [comment]
Cerrado por inactividad
