### ISSUE TITLE
lote

### ISSUE THREAD

**Issue by asapweb** [AfipSDK/afip.php#36]
Hola! Primero que nada agradecer y felicitar por este excelente desarrollo! Hemos implementado facura electronica en otros proyectos, pero con este sdk es todo muy agil.

Como tiene que ser el array para solicitar CAE a dos o mas comprobantes utilizando CreateVoucher?
Tienen un ejemplo?
Muchisimas gracias!!!

**Comment by ivanalemunioz** [comment]
Esto aun no esta implementado, de todas formas mientras tanto se puede utilizar con un simple bucle `for`

**Comment by fedevilla** [comment]
Ivan, como estas? 
Estuve tratanto de implementarlo pero me arroja el siguiente error. 
Cambie el certificado y la Key dos veces, pero me sigue arrojando el mismo error. ¿Alguna idea donde puede estar el error?

Fatal error: Uncaught Exception: SOAP Fault: soap:Server Este token no le permite actuar en representacion de la CUIT 30504507323

Agradezco cualquier ayuda.

**Comment by ivanalemunioz** [comment]
De implementar el lote?

**Comment by fedevilla** [comment]
Ivan, no, no es de Lote. 

La respuesta se genera cuando llamo a GetTaxpayerDetails
$taxpayer_details = $afip->RegisterScopeFive->GetTaxpayerDetails(33641720599);

Me devuelve 
 Este token no le permite actuar en representacion para cualquier cuit.
El Ta se genera correctamente por cada cuit consultado. La representacion en la pagina de Afip esta cargada. 

¿pensas que debe tener que ver con el crt?

**Comment by ivanalemunioz** [comment]
Estas en produccion?

**Comment by guillebalmacedaonline** [comment]
Buenas el metodo 

> $afip->RegisterScopeFive->GetTaxpayerDetails(33641720599) Solo devuelve resultados en modo PRODUCCION. En modo HOMOLOGACION O DEBUG devuelve null. Saludos
