### ISSUE TITLE
problema con PASSPHRASE

### ISSUE THREAD

**Issue by MarioOlivera** [AfipSDK/afip.php#37]
Al poner cada cosa en su lugar (archivos keys y toda la configuracion que lleva), me encuentro con este error: 

openssl_pkcs7_sign(): error getting cert

mi servidor es local en windows 10, con soap activado y todo.

el error lo da exactamente aca: en la clase principal

`//Signing TRA
		$STATUS = openssl_pkcs7_sign($this->TA_FOLDER."TRA-".$this->options['CUIT'].'-'.$service.".xml", $this->TA_FOLDER."TRA-".$this->options['CUIT'].'-'.$service.".tmp", "file://".$this->CERT,
			array("file://".$this->PRIVATEKEY, $this->PASSPHRASE),
			array(),
			!PKCS7_DETACHED
		);`

seguro es algo del PASSPHRASE, yo lo tengo por defecto, no entiendo si tendria que pone rmi clave fiscal o que, dado que siguiendo los pasos de afip genere la privada y el cert y nunca me pidio password ni nada el cmd, y en la web de homologacion todo ok.

**Comment by MarioOlivera** [comment]
Solucionado

**Comment by mendozada** [comment]
Mario, como estas ?  como solucionaste este problema , a mi me sucede lo mismo . gracias

**Comment by MarioOlivera** [comment]
en la carpeta de resources, o algo por ahi, fijate que tiene a cuit como
int o long, es un xml, pasa eso a string, y anda viendo si te tira el mismo
error que el cuit sea el que pusiste, creo que era ese mi problema

**Comment by mendozada** [comment]
Gracias  , si si  ya lo solucione era eso pase de long a string , Saludos

**Comment by MarioOlivera** [comment]
Genial diego 😎

**Comment by MrPaulD** [comment]
Hola. Tengo exactamente el mismo problema, pero no me queda claro la solución que aplicaron. Apliqué la solución que indicó mario en wsfe.wsdl y wsfe-production.wsdl, pero no logré corregir el problema... ¿Que estoy pasando por alto?

**Comment by mendozada** [comment]
Pablo, buenos dias, mira en mi caso se solucionó reemplazando en los archivos wsfe.wsdl y wsfe-production.wsdl ,

`<s:element minOccurs="1" maxOccurs="1" name="Cuit" type="s:long"/>` 
 por esta 
 `<s:element minOccurs="1" maxOccurs="1" name="Cuit" type="s:string"/>`

fijate que lo unico que cambia es el Longo por el string

Avisame si pudiste solucionarlos. 

Saludos.

**Comment by rlezamacn** [comment]
> Hola. Tengo exactamente el mismo problema, pero no me queda claro la solución que aplicaron. Apliqué la solución que indicó mario en wsfe.wsdl y wsfe-production.wsdl, pero no logré corregir el problema... ¿Que estoy pasando por alto?

Hola amigo, Por casualidad solucionaste eso?

**Comment by NicoMachado** [comment]
Hola, en mi caso estaba pasando el parametro como un string, y espera un numero!

$afip = new Afip([
            'CUIT'=> 20216663334, //<-- ojo ahi!
            'cert' => 'wsfe-sga.crt',
            'key'=> 'privada.key'
            ]);

Espero que te sirva,
saludos!

**Comment by rlezamacn** [comment]
> Hola, en mi caso estaba pasando el parametro como un string, y espera un numero!
> 
> $afip = new Afip([
> 'CUIT'=> 20216663334, //<-- ojo ahi!
> 'cert' => 'wsfe-sga.crt',
> 'key'=> 'privada.key'
> ]);
> 
> Espero que te sirva,
> saludos!


El problema estaba en regresar todo el CUIT a long  sin tocar esa parte del sdk.

Recomiendo usar el crt y la privada.key generada en vez de copiar el contenido en los archivos cert y key del sdk. Ejm:

     $afip = new Afip([
            'CUIT'=> 1111111111, //<-- ojo ahi que siga siendo logn!
            'cert' => 'APPEESSTEST.crt',
            'key'=> 'privada.key'
            ]);

 Gracias Nico.
