### ISSUE TITLE
Error al hacer Facturacion Electronica de Lotes

### ISSUE THREAD

**Issue by razielt10** [AfipSDK/afip.php#38]
Estoy realizando facturación electronica de lotes, aunque instacio varias veces un objeto de la clase Afip y justo al hacer la segunda, me da el siguiente error:

Cannot declare class ElectronicBilling, because the name is already in use in /.../vendor/afipsdk/afip.php/src/Class/ElectronicBilling.php on line 0

Este error sale ya que en el archivo Afip.php linea 250 hacen include de $file, esto se corrige con un require_once($file).

Lo edite en mi vendor, si desean puedo hacer el PR a una rama y lo mergean a master.

Por cierto me encanta la libreria.

Saludos.

**Comment by ivanalemunioz** [comment]
No te funciona con el include_once? https://github.com/AfipSDK/afip.php/blob/dbe947bb08df88f6433ebb361e0f1642bf729eea/src/Afip.php#L250

**Comment by romanopablo** [comment]
Tuve el mismo problema, pasa porque tenemos una version vieja del package. Se soluciona corriendo el comando: 

> composer update afipsdk/afip.php

**Comment by bravoga** [comment]
> Estoy realizando facturación electronica de lotes, aunque instacio varias veces un objeto de la clase Afip y justo al hacer la segunda, me da el siguiente error:
> 
> Cannot declare class ElectronicBilling, because the name is already in use in /.../vendor/afipsdk/afip.php/src/Class/ElectronicBilling.php on line 0
> 
> Este error sale ya que en el archivo Afip.php linea 250 hacen include de $file, esto se corrige con un require_once($file).
> 
> Lo edite en mi vendor, si desean puedo hacer el PR a una rama y lo mergean a master.
> 
> Por cierto me encanta la libreria.
> 
> Saludos.

Hola, usaste esta libreria para facturar con lotes?, me dirias como?
