### ISSUE TITLE
Basado en un CUIT obtener la info.

### ISSUE THREAD

**Issue by gtelesio** [AfipSDK/afip.php#39]
Hola buenos dias, quiero lograr esto : https://afip.tangofactura.com/Rest/GetContribuyenteFull?cuit=20383025290

Esta librería puede lograr eso?, por que segui la guia..  pero al invocar
$info = $afip->RegisterScopeTen->GetTaxpayerDetails(20383025290);

me retorna null, no se como hacer para que me devuelva toda la info de ese contribuyente por su numero de cuit...

**Comment by AndyGotfridt** [comment]
Hola, si, podes recuperar esa info. Ahi estas llamando al padron A10, ¿Tenes dado de alta el servicio? Recordá que el padron solo funciona en Producción no en Homologación.
Yo recien probe con  el padron  A5 y recupere lo siguiente
`{"datosGenerales":{"apellido":"TELESIO","domicilioFiscal":{"codPostal":"6700","descripcionProvincia":"BUENOS AIRES","direccion":"RIVADAVIA 657","idProvincia":1,"localidad":"LUJAN","tipoDomicilio":"FISCAL"},"estadoClave":"ACTIVO","idPersona":20383025290,"mesCierre":12,"nombre":"GONZALO PATRICIO","tipoClave":"CUIT","tipoPersona":"FISICA"},"datosMonotributo":{"actividadMonotributista":{"descripcionActividad":"SERVICIOS DE CONSULTORES EN INFORM\u00c1TICA Y SUMINISTROS DE PROGRAMAS DE INFORM\u00c1TICA","idActividad":620100,"nomenclador":883,"orden":1,"periodo":201710},"categoriaMonotributo":{"descripcionCategoria":"A LOCACIONES DE SERVICIO","idCategoria":8,"idImpuesto":20,"periodo":201710},"impuesto":{"descripcionImpuesto":"MONOTRIBUTO","idImpuesto":20,"periodo":201710}},"metadata":{"fechaHora":"2019-06-07T02:15:31.777-03:00","servidor":"aws.afip.gov.ar"}}`
Saludos!

**Comment by gtelesio** [comment]
@AndyGotfridt Hola Andy, muchas gracias por responder. Creo que estoy avanzando.. jaja pero tengo un problema ahora.. di de alta el certificado para produccion todo bien, el sdk conecta correcto.. pero.. me tira el siguiente error cuando quiero invocar este metodo..

$taxpayer_details = $afip->RegisterScopeFive->GetTaxpayerDetails(20383025290)

me tira 

![Captura de pantalla de 2019-06-08 12-26-47](https://user-images.githubusercontent.com/24793650/59150693-de405500-89fd-11e9-886f-da719bef2afd.png)

**Comment by AfipSDK** [comment]
E es un error de Afip, solo hay que esperar a que se solucione.

**Comment by LucasZdv** [comment]
Hola, estoy intentando conectarme a producción pero no lo logro, creo que pude crear los certificados correctamente según la documentación del afip, pero de ahí en mas no pude seguir. Intento hacer una consulta de cuit pero nada, obtengo el siguiente error.

Alguien sabe como puedo generar permisos a consultar el padron en producción?


`Fatal error: Uncaught Exception: SOAP Fault: ns1:coe.notAuthorized Computador no autorizado a acceder al servicio in /srv/users/afip/apps/afip-ws/public/sdk/src/Afip.php:231 Stack trace: #0 /srv/users/afip/apps/afip-ws/public/sdk/src/Afip.php(172): Afip->CreateServiceTA('wsfe') #1 /srv/users/afip/apps/afip-ws/public/sdk/src/Class/ElectronicBilling.php(328): Afip->GetServiceTA('wsfe') #2 /srv/users/afip/apps/afip-ws/public/sdk/src/Class/ElectronicBilling.php(304): ElectronicBilling->GetWSInitialRequest('FEParamGetTipos...') #3 /srv/users/afip/apps/afip-ws/public/sdk/src/Class/ElectronicBilling.php(208): ElectronicBilling->ExecuteRequest('FEParamGetTipos...') #4 /srv/users/afip/apps/afip-ws/public/sdk/app.php(13): ElectronicBilling->GetDocumentTypes() #5 {main} thrown in /srv/users/afip/apps/afip-ws/public/sdk/src/Afip.php on line 231`

**Comment by maximoleon** [comment]
@LucasZdv pudiste resolverlo? Como? Me pasa lo mismo
