### ISSUE TITLE
Warning: SoapClient::__doRequest()

### ISSUE THREAD

**Issue by LChris94** [AfipSDK/afip.php#40]
Hola estoy teniendo el siguiente error cuando quiero generar los comprobantes en homologacion es en la parte que solicita el ticket el problema, ayer funcionaba perfecto esta caido el servicio?

Warning: SoapClient::__doRequest(): SSL: Connection reset by peer in /home/.../Afip/Afip.php on line 229
SOAP Fault: HTTP Error Fetching http headers 

La linea 229 es la siguiente: $results=$client->loginCms(array('in0'=>$CMS));

Si alguien me puede ayudar se lo agradeceria muchas gracias!!

**Comment by mendozada** [comment]
Hola, Me pasa lo mismo. 

Warning: SoapClient::__doRequest(): SSL: Se ha forzado la interrupci�n de una conexi�n existente por el host remoto. in ...afip.php-master\src\Afip.php on line 217

**Comment by AfipSDK** [comment]
Es un error en los servidores de Afip, a todos nos esta apareciendo. Solo
queda esperar a que lo solucionen
