### ISSUE TITLE
A arreglar, long to string

### ISSUE THREAD

**Issue by MarioOlivera** [AfipSDK/afip.php#41]
Es comun que en la api para quien la utilice de error con el tema del cuit, cambiar long a string en el wsfe linea <s:element minOccurs="1" maxOccurs="1" name="Cuit" type="s:long"/>

**Comment by ivanalemunioz** [comment]
Eso deberias hay que pedir que lo cambien desde Afip, aqui simplemente utilizamos los WSDL provistos por ellos.
