### ISSUE TITLE
Consulta - Dudas

### ISSUE THREAD

**Issue by arieltallerpd** [AfipSDK/afip.php#42]
Me gustaría saber en que se diferencian los métodos CreateVoucher y CreateNextVoucher.
Y para que es el parámetro CbteHasta ya que no funciona para emitir varios comprobantes.
Saludos y gracias.

**Comment by ivanalemunioz** [comment]
El metodo CreateNextVoucher te pone automaticamente el numero de comprobante.
El parametro CbteHasta es para enviar lote de comprobantes pero la libreria no lo permite aun.
