### ISSUE TITLE
Al SDK le falta una clase, la de SOAPCLIENT

### ISSUE THREAD

**Issue by enocima** [AfipSDK/afip.php#43]
Buenas, la verdad que muy bueno el trabajo que hicieron, pero intentando implemantarlo, me salta un fatalError:

`Fatal error: Class 'SoapClient' not found in C:\xampp\htdocs\Trabajo\AFIP\ws\afip.php-master\src\Afip.php on line 223`

revistando todos los archivos, no lo encuentro y creo que falta.... podran subirlo???
gracias

**Comment by ivanalemunioz** [comment]
SoapClient es una extension de PHP https://www.php.net/manual/es/intro.soap.php debes activarla para poder usarla
