### ISSUE TITLE
Nombre incorrecto en CUIT

### ISSUE THREAD

**Issue by cybersantu** [AfipSDK/afip.php#44]
Buenas tardes. Estoy ejecutando este código

$taxpayer_details = $afip->RegisterScopeFive->GetTaxpayerDetails(20125778705);

Retorna bien los datos, pero el nombre del contribuyente está equivocado. De hecho, pasa con todos los CUITs que pongo. Otra cosa que sucede, es que cuando ingreso CUITs de personas fìsicas, devuelve null.

¿Qué puedo estar haciendo mal?

Muchas gracias

**Comment by ivanalemunioz** [comment]
En testing te devuelve datos falsos el padron. Para hacer consultas a CUITs de personas fisicas debes usar el padron alcance 13.

**Comment by cybersantu** [comment]
Muchas gracias Ivan
