### ISSUE TITLE
Consulta Error 500

### ISSUE THREAD

**Issue by mchisnerman3** [AfipSDK/afip.php#45]
Hola, como estan?, les hago una consulta, tratando de implementar la API, siempre obtengo un error 500 y no me muestra nada mas. Evidentemente, estoy haciendo algo mal, pero no se que.
Que puedo probar?
Gracias

**Comment by ivanalemunioz** [comment]
Debes mostrar los errores de PHP para poder saber el error real https://www.anerbarrena.com/mostrar-errores-php-608/
