### ISSUE TITLE
Soporte para CAEA Contingencia

### ISSUE THREAD

**Issue by dieduk89** [AfipSDK/afip.php#47]
Estoy implementando un sistema de facturación y note que hace falta un parámetro para el metodo FECAEARegInformativo cuando el punto de venta es de tipo CAEA Contingencia. Según el manual para el desarrollador de AFIP el parámetro CbteFchHsGen es obligatorio si el punto de venta es CONTINGENCIA CAEA (Código de error 1440)

En los archivos del repositorio no esta contemplado el parámetro CbteFchHsGen, para hacerlo funcionar tuve que editar los documentos WSDL y añadir el elemento XML manualmente.

**Comment by ivanalemunioz** [comment]
Que extraño, los XML son descargados desde las url del Web Service, te fijaste si ahi estaba el parametro?

**Comment by dieduk89** [comment]
Si es bastante extraño, acabo de revisar el xml del servicio: 
https://servicios1.afip.gov.ar/wsfev1/service.asmx?WSDL
y efectivamente ahí si se encuentra el parámetro CbteFchHsGen, pero en los archivos de la librería no están en ningún lado.

**Comment by ivanalemunioz** [comment]
Quiza en alguna actualizacion lo cambiaron, deberia revisarlos nuevamente

**Comment by matiasperrone** [comment]
@dieduk89 fijate si podés subir un pull request! a mi me serviría también!

**Comment by ivanalemunioz** [comment]
Listo, ya quedo actualizado en el commit 3b39df3bc511905135438cdadc62850363d7b5e2
