### ISSUE TITLE
openssl_pkcs7_sign(): error creating PKCS7 structure!

### ISSUE THREAD

**Issue by arieltallerpd** [AfipSDK/afip.php#48]
Hola veamos si alguien me puede ayudar con este problema. Generé un certificado digital para el entorno de producción tal como indica la documentación de AFIP pero estoy recibiendo el siguiente error:

> <b>Warning</b>:  openssl_pkcs7_sign(): error creating PKCS7 structure! in <b>/var/www/tefacturo1/afip.php/src/Afip.php</b> on line <b>207</b><br />
> <br />
> <b>Notice</b>:  Trying to get property 'token' of non-object in <b>/var/www/tefacturo1/afip.php/src/Class/ElectronicBilling.php</b> on line <b>332</b><br />
> <br />
> <b>Notice</b>:  Trying to get property 'sign' of non-object in <b>/var/www/tefacturo1/afip.php/src/Class/ElectronicBilling.php</b> on line <b>333</b><br />
> <br />
> <b>Fatal error</b>:  Uncaught Exception: (600) ValidacionDeToken: Parametro nulo o vacio (token) in /var/www/tefacturo1/afip.php/src/Class/ElectronicBilling.php:364
> Stack trace:
> #0 /var/www/tefacturo1/afip.php/src/Class/ElectronicBilling.php(308): ElectronicBilling-&gt;_CheckErrors('FECompUltimoAut...', Object(stdClass))
> #1 /var/www/tefacturo1/afip.php/src/Class/ElectronicBilling.php(41): ElectronicBilling-&gt;ExecuteRequest('FECompUltimoAut...', Array)
> #2 /var/www/tefacturo1/classes/afip_methods.php(6): ElectronicBilling-&gt;GetLastVoucher('2', '11')
> #3 /var/www/tefacturo1/classes/afip_methods.php(20): Afip_methods-&gt;getLastVoucher(Object(Afip), '2', '11')
> #4 /var/www/tefacturo1/controllers/registerVoucher.php(13): Afip_methods-&gt;numeroCbte(Object(Afip), 1, '2', '11')
> #5 {main}
>   thrown in <b>/var/www/tefacturo1/afip.php/src/Class/ElectronicBilling.php</b> on line <b>364</b><br />

He investigado un poco y dicen ser problema en el certificado, pero ya lo he vuelto a generar y en el Administrador de certificados digitales indica estado válido pero sigo teniendo el mismo problema.

Gracias y saludos!

**Comment by ivanalemunioz** [comment]
Pudiste resolverlo? Que era?

**Comment by arieltallerpd** [comment]
No estoy seguro pero después de algunos intentos el error cambió a : 

> openssl_pkcs7_sign(): error getting private key

La solución fue cambiar el directorio donde se ubicaba el certificado y la clave privada, una pavada pero no entendí cual era el problema cambié de un directorio con el nombre "20334445551" a "Ramon" (ejemplo).

**Comment by ManuelAgustinLucero** [comment]
Hola @arieltallerpd estoy con el mismo problema, me podrias ayudar?

**Comment by fertandil87** [comment]
@ManuelAgustinLucero a mi me paso, y cambie el nombre del certificado del csr al pem que es el que lleva la clave

**Comment by arieltallerpd** [comment]
Hola @ManuelAgustinLucero disculpame por no responder. Esto me ha sucedido unas tres veces y lo he solucionado volviendo a generar el pedido y volver a generar el certificado en AFIP

**Comment by johnnestebann** [comment]
A mi me sigue pasando, generé como 3 certifcados, y no hay manera de pasar el openssl_pkcs7_sign(): error getting private key

**Comment by wa05** [comment]
> A mi me sigue pasando, generé como 3 certifcados, y no hay manera de pasar el openssl_pkcs7_sign(): error getting private key

Hola pudiste resolverlo ?

**Comment by chiodora1** [comment]
Hola, me estoy quemando la cabeza con la facturacion electronica en PHP. Estoy migrando mis sistemas a PHP y me encuentro con el siguiente problema " Warning: openssl_pkcs7_sign(): error creating PKCS7 structure! in C:\xampp\htdocs\neofactura13\wsaa.php  "
Ya hice de todo y no puedo dar con el problema. Alguien me puede dar una mano con esto. Muchas gracias

**Comment by chiodora1** [comment]
Hola, me estoy quemando la cabeza con la facturacion electronica en PHP. Estoy migrando mis sistemas a PHP y me encuentro con el siguiente problema
Warning: openssl_pkcs7_sign(): error creating PKCS7 structure! in C:\xampp\htdocs\neofactura13\wsaa.php 
la linea del programa que tira el error es esta

$infilename = $this->base_dir . "/" . $this->cuit . '/' . $this->service . "/token/TRA.xml";
$outfilename = $this->base_dir . "/" . $this->cuit . '/' . $this->service . "/TRA.tmp";
$headers = array();
$flags = !PKCS7_DETACHED;
$status = openssl_pkcs7_sign($infilename, $outfilename, $this->cert, $this->privatekey, $headers, $flags);

Ya hice de todo y no puedo dar con el problema. Alguien me puede dar una mano con esto. Muchas gracias

**Comment by arieltallerpd** [comment]
> Hola, me estoy quemando la cabeza con la facturacion electronica en PHP. Estoy migrando mis sistemas a PHP y me encuentro con el siguiente problema
> Warning: openssl_pkcs7_sign(): error creating PKCS7 structure! in C:\xampp\htdocs\neofactura13\wsaa.php
> la linea del programa que tira el error es esta
> 
> $infilename = $this->base_dir . "/" . $this->cuit . '/' . $this->service . "/token/TRA.xml";
> $outfilename = $this->base_dir . "/" . $this->cuit . '/' . $this->service . "/TRA.tmp";
> $headers = array();
> $flags = !PKCS7_DETACHED;
> $status = openssl_pkcs7_sign($infilename, $outfilename, $this->cert, $this->privatekey, $headers, $flags);
> 
> Ya hice de todo y no puedo dar con el problema. Alguien me puede dar una mano con esto. Muchas gracias

Hola, te recomendaría revisar lo siguiente: 

1. Revisar los permisos en carpetas pero en tu caso veo que estás en Windows así que dudo que sea el problema ya que si Xampp se ejecuta como administrador obtenés todos los permisos. También que el directorio donde se guarda el certificado digital, clave privada y tokens no contenga caracteres especiales.
2. Probar cambiar el directorio del certificado digital, clave privada y tokens. Parece irracional pero en un caso me funcionó.
3. Si sigue fallando intentar volver a generar el pedido.pem y clave privada, asegurarse que se está proporcionando bien el cuit y la razón social no contiene acentos ni caracteres especiales, luego volver a generar el certificado digital. Antes de colocar el nuevo certificado digital y la nueva clave privada asegúrate de eliminar los viejos certificado digital, clave privada y tokens del directorio de destino.

Espero que ayude, saludos!

**Comment by chiodora1** [comment]
Hola Ariel, desde ya muchas gracias, ahora voy a probar con eso y te informo el resultado. Gracias

**Comment by skpao** [comment]
Sé que es un poco tarde mi comentario, pero igual lo dejor por si a alguien más le sucede.
En mi caso lo que pasaba era que había reemplazado el .crt, pero me faltaba hacer lo mismo con .key.
Al final esa fue mi solución, reemplazar los 2 archivos con los nuevos generados.
Saludos.
