### ISSUE TITLE
Como obtengo percepción de IIBB?

### ISSUE THREAD

**Issue by gusgeek** [AfipSDK/afip.php#50]
Hola buenas noches.
Gran proyecto y sumamente agradecido por tal.

Quisiera saber si a traves de este, puedo obtener aquel cliente que es agente de percepción y calcular el mismo.

Desde ya, gracias.

**Comment by guillebalmacedaonline** [comment]
Hola buenos dias, por lo que tengo entendido y espero no equivocarme IIBB depende de cada provincia, eso deberias consultar a tu contador o en el sitio de renta correspondiente a tu provincia. Saludos espero que te sirva de ayuda.

**Comment by ivanalemunioz** [comment]
@gusgeek Pudiste resolverlo?

**Comment by gusgeek** [comment]
No aún nada

**Comment by ivanalemunioz** [comment]
Tal como dijo Guillermo debes averiguar como es para la provincia donde te encuentras
