### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by alegalicia** [AfipSDK/afip.php#52]
Buenos días Ivan, 
Antes que nada te comento que me parece genial tu aporte estoy hace un par de días tratando de comprender el funcionamiento del SOAP y como consumirlo con php, con tu aporte se me facilito bastante, quería consultarte si hay que tener de manera obligada para hacer el método testing contar con la crt y key?

Gracias.-

**Comment by guillebalmacedaonline** [comment]
Hola @alegalicia si es necesario los certificados para homologacion para hacer testing, lo unico que no te va a funcionar en testing es la consulta a padron de afip. Pero la parte de factura electronica es muy similar a la de produccion. Te paso documentacion para que puedas ver como crear certificado de testing en afip.
http://www.afip.gob.ar/ws/WSASS/WSASS_como_adherirse.pdf
http://www.afip.gob.ar/ws/WSASS/html/index.html

saludos.
