### ISSUE TITLE
Facturas de Exportacion E . Cod 19 y 21

### ISSUE THREAD

**Issue by aledc7** [AfipSDK/afip.php#53]
Hola estimados, antes que nada __GRACIAS__ por esta librería! .   

Quería consultarles si tiene implementado alguna librería para realizar facturas de Exportación tipo "E"  __(cód. 19)__   y Notas de crédito de Exportación __(cód. 21)__.   

Gracias de nuevo, y Saludos!!!

- [x]  https://github.com/aledc7

**Comment by ivanalemunioz** [comment]
Hola Alejandro, no, no tenemos implementado ningun web service que lo permita

**Comment by AleAmla987** [comment]
Hola tienen pensado implementarlo en algun momento? es muy necesario para mi y claro podría abonar esas hora de trabajo =D

**Comment by aledc7** [comment]
> Hola tienen pensado implementarlo en algun momento? es muy necesario para mi y claro podría abonar esas hora de trabajo =D

Ale yo finalmente lo pude implementar, lo tengo funcionando en producción, escribime y te ayudo

**Comment by JuanjoArmellino** [comment]
Hola Que tal, buenos dias.
alguien sabe si hubo actualizaciones sobre la factura de exportacion para el webservice WSFEXv1 ? tengo que hacer facturas E a clientes en tierra del fuego y no he podido avanzar

saludos
Juanjo

**Comment by AleAmla987** [comment]
> Hola Que tal, buenos dias. alguien sabe si hubo actualizaciones sobre la factura de exportacion para el webservice WSFEXv1 ? tengo que hacer facturas E a clientes en tierra del fuego y no he podido avanzar
> 
> saludos Juanjo

Mandame un mensaje al +5493884070022
