### ISSUE TITLE
Web Service Constatar Comprobantes

### ISSUE THREAD

**Issue by sebastiancorrea81** [AfipSDK/afip.php#54]
Hola buenas tardes, tengo la intencion de implemetar el servicio de contar comporbantes, ya que en la apicacion que estoy desarrollando requiere constatar la validez de las facturas electroncas. Quisiera saber si hay alguien ya trabajando en eso. Gracias

**Comment by guillebalmacedaonline** [comment]
Hola si necesitas validar la factura electronica emitida te recomendaria utilizar la funcion **GetVoucherInfo**:

$voucher_info = $afip->ElectronicBilling->GetVoucherInfo((int) $_POST['numComprob'],(int) $_POST['ptoVenta'],(int) $_POST['tipoComprob']); 

if($voucher_info === NULL){
    echo 'El comprobante no existe o no es valido';
}
else{
    echo 'Esta es la información del comprobante:';
    echo '<pre>';
    print_r($voucher_info);
    echo '</pre>';
}

saludos espero que te sirva.

**Comment by sebastiancorrea81** [comment]
Muchas Gracias por tu respuesta, este service me permite consultar cualquier comprobante y validarlo o solo los emitidos con mi cuit? Slds

**Comment by SERBice** [comment]
Te permite ver los comprobantes emitidos por el punto de venta del web
service, no para comprobantes de otro punto de venta ni de otro cuit.
