### ISSUE TITLE
Detectando SoapTimeout 

### ISSUE THREAD

**Issue by JuanjoArmellino** [AfipSDK/afip.php#57]
Hola buen dia
me parece excepcional el trabajo que has hecho con esta API, te felicito
mi consulta va orientada a como manejar los soaptimeout cuando el servidor esta caido o directamente no responde..  porque aunque tengo un tiempo de ejecucion en mi script de 180 seg, mi servidor me devuelve error 504 a los 30 segundos, por lo que anduve leyendo es complicado cuando se usa soapclient hacer las detecciones.
hay algun control sugerido para el uso de la API ?

saludos
Juanjo

**Comment by ivanalemunioz** [comment]
Hola Juanjo, si el servidor no responde o esta caido deberias de hacer un reintento
