### ISSUE TITLE
me tira fatal error una consulta afip 13

### ISSUE THREAD

**Issue by yopicon2** [AfipSDK/afip.php#59]
Fatal error: Uncaught Exception: SOAP Fault: soap:Server Persona inactiva in Afip.php:402 Stack trace: #0
Afip.php(382): AfipWebService->_CheckErrors('getPersona', Object(SoapFault)) #1
/Class/RegisterScopeThirteen.php(80): AfipWebService->ExecuteRequest('getPersona', Array) #2

Y varios mas. Esto al consultar este cuil: 20002515173
La consulta 5 no rompe.

Parece que no esta activa la personal. El problema es que no la puedo atrapar la excepción, y la pagina me tira error.

Mis conocimientos de php son mediocres. Agradecería la ayuda!

**Comment by ivanalemunioz** [comment]
Probaste con try.. catch.. ?

**Comment by AndyGotfridt** [comment]
Proba con try como dijo ivanalemunioz
``    try{
        $padron = $afip->RegisterScopeThirteen->GetTaxpayerDetails('cuit');
    } catch (Exception $e) {
        echo $e->getMessage();
    }``

Te devuelve el error:

> SOAP Fault: soap:Server Persona inactiva null
