### ISSUE TITLE
se usa con framework?

### ISSUE THREAD

**Issue by maximoleon** [AfipSDK/afip.php#60]
Hola! Esta desarrollado para tener q usarlo con un framework determinado? O puede usarse directamente?

**Comment by ivanalemunioz** [comment]
Podes usarlo solo o integrarlo con cualquier framework

**Comment by maximoleon** [comment]
Gracias por responder! Se puede crear un comprobante con varios detalles? (Detalles de productos vendidos)

**Comment by ivanalemunioz** [comment]
Si, es indiferente ya que los detalles no se envian a AFIP, solo los totales
