### ISSUE TITLE
CERT y Key

### ISSUE THREAD

**Issue by gusgeek** [AfipSDK/afip.php#62]
Hola! Hay forma de usar el CERT y el KEY como String en este SDK?

Hay forma de automatizar la renovacion de estos ?

**Comment by ivanalemunioz** [comment]
@gusgeek no, no hay forma de usarlos como string, tampoco hay una forma de automatizar la renovación implementada

**Comment by gusgeek** [comment]
Uuuuufff, bueno gracias
