### ISSUE TITLE
RegisterScopeFive - Fatal error: Uncaught exception 'Exception' with message 'SOAP Fault: HTTP Error Fetching http headers ' 

### ISSUE THREAD

**Issue by ConradGalli** [AfipSDK/afip.php#65]
Warning: SoapClient::__doRequest(): SSL: Connection reset by peer in /Afip.php on line 374

Fatal error: Uncaught exception 'Exception' with message 'SOAP Fault: HTTP Error Fetching http headers ' 

Alguna idea?

**Comment by ivanalemunioz** [comment]
Es un error temporal, probaste nuevamente?

**Comment by ConradGalli** [comment]
> Es un error temporal, probaste nuevamente?

Si, ahi levanto, voy a armar una clase para tener un estado de esto
