### ISSUE TITLE
Factura Items

### ISSUE THREAD

**Issue by fede90** [AfipSDK/afip.php#69]
Hola, sigo probando la librería. No veo forma de poner varios items para la factura (Producto/Servcio, Catidad, U. Medida, Precio Unitario, Subtotal)

Es posible hacer esto con la librería?

**Comment by ivanalemunioz** [comment]
No es necesario, Afip solo pide los totales

**Comment by fede90** [comment]
Gracias por la respuesta! 
Entiendo que es suficiente con los totales, pero con la última versión de la librería no se puede enviar items?

**Comment by ivanalemunioz** [comment]
El web service utilizado no da la posibilidad de enviar los items. No es un tema de la libreria

**Comment by fede90** [comment]
Una última pregunta, hay algún campo para poner una descripción a la factura?

**Comment by ivanalemunioz** [comment]
No, no hay
