### ISSUE TITLE
Error al Generar Invoices 

### ISSUE THREAD

**Issue by sebastiancorrea81** [AfipSDK/afip.php#70]
Hola buenos dias, estoy teniendo un problema al querer procesar gran voumen de facturas. El proceso se esta llamando desde un cron y despues de ejecutarse sin problemas durante un tiempo, empieza a dar un error de conexion al host (SOAP Fault).

Quisiera saber si es uan restriccion de AFIP o algo asi.......

Mcuhas Gracias

**Comment by ivanalemunioz** [comment]
Cual es el error completo que te da?

**Comment by sebastiancorrea81** [comment]
"SOAP Fault: http could not connect to host", ese es el error que me arroja al tiempo de estar generando facturas correctamente. Uso el método CreateNextVoucher.

**Comment by ivanalemunioz** [comment]
El problema es que no se puede conectar al servidor. El firewall no te estara bloqueando la conexion?

**Comment by sebastiancorrea81** [comment]
Te describo el problema, cuando se larga el proceso de facturar empieza correcto y genera las facturas sin sin problemas. Despues de un rato de estar facturando me devuelve ese error. Si fuera problema de firewall no se conectaria nunca....no?. Tendra que ver el volumen de facturas?

**Comment by ivanalemunioz** [comment]
Mmm quiza deberias comunicarte con Afip aver si ellos te lo estan bloqueando

**Comment by sebastiancorrea81** [comment]
Esa era la siguiente pregunta. Es posible que afip te bloquee cuando estas generando mucho volumen?. He estado investigando sobre la facturacion por lotes. Eso lo puedo hacer con este paquete?

**Comment by ivanalemunioz** [comment]
Nunca escuche de que a alguien le pasara, por eso te digo que lo consultes con ellos. No, esta libreria no tiene implementada la facturacion por lotes

**Comment by sebastiancorrea81** [comment]
Ok. Muchas Gracias por tu rapida respuesta! Te agradezco un monton. Abz
