### ISSUE TITLE
No me genera la factura

### ISSUE THREAD

**Issue by luzbelitolfc** [AfipSDK/afip.php#71]
Hola, estoy intentando crear mi primer factura y no tengo respuesta. Así armo el array:

`$data = array(
            'CantReg' 		=> 1, // Cantidad de comprobantes a registrar
            'PtoVta' 		=> 3, // Punto de venta
            'CbteTipo' 		=> 11, // Tipo de comprobante (ver tipos disponibles) 
            'Concepto' 		=> 2, // Concepto del Comprobante: (1)Productos, (2)Servicios, (3)Productos y Servicios
            'DocTipo' 		=> 80, // Tipo de documento del comprador (ver tipos disponibles)
            'DocNro' 		=> 20285683182, // Numero de documento del comprador
            'CbteDesde' 	=> 1, // Numero de comprobante o numero del primer comprobante en caso de ser mas de uno
            'CbteHasta' 	=> 1, // Numero de comprobante o numero del ultimo comprobante en caso de ser mas de uno
            'CbteFch' 		=> intval(date('Ymd')), // (Opcional) Fecha del comprobante (yyyymmdd) o fecha actual si es nulo
            'ImpTotal' 		=> 1, // Importe total del comprobante
            'ImpTotConc' 	=> 1, // Importe neto no gravado
            'ImpNeto' 		=> 0, // Importe neto gravado
            'ImpOpEx' 		=> 0, // Importe exento de IVA
            'ImpIVA' 		=> 0, //Importe total de IVA
            'ImpTrib' 		=> 0, //Importe total de tributos
            'FchServDesde' 	=> NULL, // (Opcional) Fecha de inicio del servicio (yyyymmdd), obligatorio para Concepto 2 y 3
            'FchServHasta' 	=> NULL, // (Opcional) Fecha de fin del servicio (yyyymmdd), obligatorio para Concepto 2 y 3
            'FchVtoPago' 	=> NULL, // (Opcional) Fecha de vencimiento del servicio (yyyymmdd), obligatorio para Concepto 2 y 3
            'MonId' 		=> 'PES', //Tipo de moneda usada en el comprobante (ver tipos disponibles)('PES' para pesos argentinos) 
            'MonCotiz' 		=> 1,     // Cotización de la moneda usada (1 para pesos argentinos)   
        );`

**Comment by ivanalemunioz** [comment]
Podrias mostrar algo mas del codigo?
Activaste que PHP te puestre los errores?

```` PHP
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
````
