### ISSUE TITLE
Problema con Token y PKCS7

### ISSUE THREAD

**Issue by gusgeek** [AfipSDK/afip.php#72]
Buenas tardes, vengo teniendo este inconveniente con el SDK

```
<b>Warning</b>:  openssl_pkcs7_sign(): error getting private key in <b>...\services\afip\Afip.php</b> on line <b>208</b><br />
<br />
<b>Notice</b>:  Trying to get property 'token' of non-object in <b>...\services\afip\Class\ElectronicBilling.php</b> on line <b>332</b><br />
<br />
<b>Notice</b>:  Trying to get property 'sign' of non-object in <b>...\services\afip\Class\ElectronicBilling.php</b> on line <b>333</b><br />
<br />
<b>Fatal error</b>:  Uncaught Exception: (600) ValidacionDeToken: Parametro nulo o vacio (token) in ...\services\afip\Class\ElectronicBilling.php:364
Stack trace:
#0 ...\services\afip\Class\ElectronicBilling.php(308): ElectronicBilling-&gt;_CheckErrors('FECompUltimoAut...', Object(stdClass))
#1 ...\services\afip\Class\ElectronicBilling.php(41): ElectronicBilling-&gt;ExecuteRequest('FECompUltimoAut...', Array)
#2 ...\notadeventa\post.php(238): ElectronicBilling-&gt;GetLastVoucher('0006', 13)
#3 {main}
  thrown in <b>...\services\afip\Class\ElectronicBilling.php</b> on line <b>364</b><br />
```

Los directorios donde esta invocando los Archivos funcionaron hasta ayer, incluso el TA.XML lo esta generando y lo deja alojado en el directorio pertinente. Que puede estar fallando?

**Comment by ivanalemunioz** [comment]
no hiciste ningun cambio?

**Comment by ivanalemunioz** [comment]
tiene permisos de lectura y escritura?

**Comment by gusgeek** [comment]
Hola Ivan, estoy en Windows, no ajuste ningun permiso. Exactamente lo acabo de resolver poniendolo en el directorio original del SDK, pero en donde configuro los directorios de la plataforma me da inconveniente actualmente, entendiendo que hasta hace unos dias esto funciono....

**Comment by gusgeek** [comment]
Algún problema de directorios debo tener, porque fue inminente y el code no se actualizo. Verificare si no es que por ahí halla algún inconveniente que no vea yo.

**Comment by ivanalemunioz** [comment]
Fijate bien las rutas

**Comment by gusgeek** [comment]
Voy a eso, te aviso
