### ISSUE TITLE
openssl_pkcs7_sign(): error getting cert 

### ISSUE THREAD

**Issue by rodcibils** [AfipSDK/afip.php#73]
openssl_pkcs7_sign(): error getting cert in Afip.php on line 210

Al intentar realizar una request al WS de Homologacion. Los archivos .key (clave privada generada) y .pfx (clave generada por AFIP al obtener autorizacion) fueron renombrados como key y cert respectivamente y colocados en la carpeta "Afip_res" dentro del path "vendor/afipsdk/afip.php/src/Afip_res" del proyecto, ya que descargue la libreria via Composer.

Fueron revisados los permisos de la respectiva carpeta para lectura y escritura y tambien se intento utilizar realpath sin exito en la parte del path del certificado. Probe tambien modificar el campo Cuit de long a string segun sugeria una issue cerrada con un problema similar, sin exito.

Entorno:
Ubuntu Server 20.04 LTS
PHP 7.4.3

**Comment by rodcibils** [comment]
Problema solucionado. El certificado que se estaba utilizando era incorrecto, por lo cual no era un problema del SDK. Utilizando el certificado pem correcto se resolvio el problema. Issue cerrada.

**Comment by KatiaSishost** [comment]
Para extender la solución:
Se deben colocar los certificados generados y la key en:

Directorio: afipsdk/src/Afip_res
Archivos: cert y key respectivamente (sin extension)
