### ISSUE TITLE
Por lo general este error suele ser de tipeo humano (no ponen el numero o fecha correctas)  quiero aclarar que hasta ahora no me he visto de que a alguien le salga este error por error (valga la redundancia) de los servidores de AFIP.

### ISSUE THREAD

**Issue by puentesdiaz** [AfipSDK/afip.php#74]
Por lo general este error suele ser de tipeo humano (no ponen el numero o fecha correctas)  quiero aclarar que hasta ahora no me he visto de que a alguien le salga este error por error (valga la redundancia) de los servidores de AFIP.

_Originally posted by @AfipSDK in https://github.com/AfipSDK/afip.php/issues/17#issuecomment-425689549_

Tenemos un lote de facturas a generar con la misma fecha, y hemos generado un factura con fecha posterior a la real, y ahora las facturas subsiguientes que tienen la fecha correcta no pueden ser generadas ya que nos pide que tengan una fecha posterior.
Como puedo anular la factura que tiene la fecha errónea para poder usar la fecha original ?

**Comment by ivanalemunioz** [comment]
Todos los comprobantes deben tener una fecha posterior entre si, no es posible borrar una

**Comment by puentesdiaz** [comment]
la Solucion argenta, fue crear un nuevo Punto de Venta

**Comment by ivanalemunioz** [comment]
jajaja bien argento
