### ISSUE TITLE
datos para mejorar y tomar cotizacion de las monedas

### ISSUE THREAD

**Issue by vaosceco** [AfipSDK/afip.php#75]
en class ElectronicBilling
public function GetCotizacion($mon_id)
    {
        $req = array(
            'MonId' 	=> $mon_id
        );

        return $this->ExecuteRequest('FEParamGetCotizacion', $req);
    }

**Comment by gusgeek** [comment]
Hola como estas! para esto quiero contarte que tengo un SDK para obtener la cotizacion del dolar de distintas entidades 

https://github.com/gusgeek/SAPIDK-Dolar

saludos

> en class ElectronicBilling
> public function GetCotizacion($mon_id)
> {
> $req = array(
> 'MonId' => $mon_id
> );
> 
> ```
>     return $this->ExecuteRequest('FEParamGetCotizacion', $req);
> }
> ```

**Comment by vaosceco** [comment]
Muy interesante, gracias
----------------------------------------------------
Maximiliano Petersen

**Comment by ivanalemunioz** [comment]
Gracias
