### ISSUE TITLE
problema con el cuit del comprador en homologacion

### ISSUE THREAD

**Issue by postre** [AfipSDK/afip.php#77]
Hola me encontre con un problema en homologacion, en produccion aun no se.. por que no lo probe.. 
cuando envio el cuit 20268261053 me devuelve esto 

Uncaught Exception: (10015) Factura B (CbteDesde igual a CbteHasta), DocTipo: 80, DocNro 2147483647 no se encuentra registrado en los padrones de AFIP

me esta transformando el cuit a 2147483647  luego de un rato de batallar... entre al archivo wsfe.wsdll y cambie el tipo de dato del DocNro de long a string y salio andando.

name="DocNro" type="s:string"

la pregunta es como ven ustedes esto.. ya que no me animo a hacerlo en produccion.

Gracias.

**Comment by SERBice** [comment]
El número 2147483647 es el máximo para un entero con signo en arquitectura
de 32 bits.
Probablemente PHP esta corriendo en arquitectura de 32bits o estas
realizando alguna operacion tratando al numero como un int32 (Entero de
32bits)
No es un problema de AfipSDK aparentemente.
