### ISSUE TITLE
Problema con Token y PKCS7 

### ISSUE THREAD

**Issue by nikkotw** [AfipSDK/afip.php#78]
Estoy implementando en Laravel afip y la realidad es que me tira el siguiente error 
ErrorException
openssl_pkcs7_sign(): error creating PKCS7 structure!
 si me pueden ayudar?

**Comment by ivanalemunioz** [comment]
Pusiste el certificado y key en el lugar correcto?

**Comment by nikkotw** [comment]
si si correcto, Puse los certificados donde van y funciona todo bien el problema pasa cuando paso a produccion!

**Comment by ivanalemunioz** [comment]
el problema tiene pinta de ser que no esta leyendo bien el certificado o la key

**Comment by nikkotw** [comment]
magicamente funciono no toque no hice nada y salio andando
