### ISSUE TITLE
SoapClient::__doRequest(): SSL: Se ha forzado la interrupci�n de una conexi�n existente por el host remoto.

### ISSUE THREAD

**Issue by nikkotw** [AfipSDK/afip.php#79]
Error Al querer generar una factura o querer ver el estado del servidor arroja eso, como puedo manejar esa excepcion?

**Comment by mendozada** [comment]
Tengo el mismo Error

SoapClient::__doRequest(): SSL: Connection reset by peer in

**Comment by juanig98** [comment]
Estoy igual. Fue luego de la actualización del CLI

ErrorException: SoapClient::__doRequest(): SSL: Connection reset by peer

**Comment by mendozada** [comment]
Es problema de Afip , porque recien intente y empezo a funcionar correctamente

**Comment by juanig98** [comment]
Efectivamente, ya está solucionado!

**Comment by nikkotw** [comment]
Genial Gracias, consulta alguien tiene los codigos de error q arroja afip? es para manejar las excepciones
