### ISSUE TITLE
Factura credito

### ISSUE THREAD

**Issue by jubagg** [AfipSDK/afip.php#81]
Buenos dias, antes que nada agredecer este SDK que es fantastico!, estaria bueno que para desarrolladores que estan empezando puedan ofrecernos la posibilidad de donar $$ a la cuasa con lo que podamos para que mejore dia a dia el desarrollo del mismo.

mi pregunta es la siguiente, el SDK cuenta con la capacidad de generar facturas credito??

Desde ya muchas gracias a todo el equipo

**Comment by ivanalemunioz** [comment]
Sisi, se pueden generar facturas de credito con el SDK

**Comment by jubagg** [comment]
y consulto, para usar el web service solo sigo los paso o tengo q agregar algo mas? porque me esta tirando error de SOAP y no puedo probar el sistema

**Comment by ivanalemunioz** [comment]
Debes agregegar el comprobante asociado. En  #82 tenes mas info
