### ISSUE TITLE
Mensaje AFIP: 10197 Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.

### ISSUE THREAD

**Issue by ramonrxven** [AfipSDK/afip.php#82]
hola, quería hacerles una consulta, me esta apareciendo este mensaje cuando intento generar una nota de crédito,
"1**0197  Si el comprobante es Débito o Crédito, enviar estructura CbteAsoc o PeriodoAsoc.**"
por lo que puedo entender en el cuerpo del mensaje me falta incluir la estructura CbteAsoc, pero no se como hacerlo con el SDK,
si pudieran arrojar algo de luz en este tema mucho se lo agradecería, ya tengo un rato atascado.

saludos

**Comment by federicoromani** [comment]
Hola ramonrxven, ahora es obligatorio asociar un comprobante. Los atributos de CbteAsoc son: Tipo, PtoVta y Nro

**Comment by ramonrxven** [comment]
hola @federicoromani, gracias por el aporte, mi atasco pasa por que no se como incorporar los atributos os atributos de CbteAsoc son: Tipo, PtoVta y Nro en el mensaje para crear el documento.

si pudieras indicarme como armarlo seria genial,

saludos

**Comment by jenanni** [comment]
Debes incluir en el json que que envies como paremetro al metodo createVoucher lo siguiente:

CbteAsoc: [{
   Tipo: 7, 
   PtoVta: 1,
   Nro: 485
}]

Obviamente en Tipo, PtoVta y Nro pones los datos que correspondan. Si tienes que asociar mas de un comprobantes, simplementes pones otro objeto con los datos, como otro elemento del array

**Comment by ramonrxven** [comment]
> CbteAsoc: [{
>    Tipo: 7, 
>    PtoVta: 1,
>    Nro: 485
> }]

perfecto funcionó, muchas gracias por tu ayuda,
gracias a todos por el apoyo, tenía días atascado con esto
saludos

**Comment by arielarce2** [comment]
Hola les hago una consulta, no se como integrar el json a la estructura del voucher, alguien me podría ayudar , gracias !

**Comment by mendozada** [comment]
hola Ariel , podrias compartir parte de tu codigo para ver cual es tu problema.

**Comment by arielarce2** [comment]
Hola , muchas gracias por tu respuesta, ya lo pude resolver !

**Comment by costajo** [comment]
Hola. Tengo un sistema de Brasil que genera un txt y otro de Argentina que toma el txt y solicita CAE. No tengo mas contacto con la empresa de Brasil. Hay como agregar en el txt lo que falta?? no se como hacer. Alguien puede me dar una mano? Mi problema é que no tengo como solicitar a empresa de brasil que lo agregue en el txt.. lo tengo que agregar a mano yo y se me complica un poco. si alguien puede me indicar que línea, y columna.. O envío uno por mail y me devuelven para tener cono ejemplo??????que si yo.

**Comment by maxivgg** [comment]
Hola, me salio el mismo mensaje que @ramonrxven "Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.null"
Tengo casos que debo asignar un PeriodoAsoc como puedo hacerlo?
Gracias!!

**Comment by mendozada** [comment]
hola Maxivgg , en mi estructura de datos yo tuve que agregar  los datos para los Comprobantes Asociados  y me resulto , 

Te pego mi codigo php de como lo hice
`
if( $bandera == 'Nc'){
                    $data['CbtesAsoc'] =  array(
                          'CbteAsoc' => array('Tipo' => $fact_asoc->Tipo,
                                                           'PtoVta' => $fact_asoc->PtoVta,
                                                           'Nro' => $fact_asoc->Nro,
                                                           'Cuit' => $empresa->cuit,
                                                           'CbteFch' => intval(date('Ymd', strtotime($fact_asoc->fecha)))
                                              ));
                 }
`
Espero te sea de ayuda . saludos

**Comment by mendozada** [comment]
Costajo ,  y es sistema de argentina que toma ese txt , ese ¿ podes modiicar los datos que presenta a WS de afip ??  , si podes copia  el contenido del txt.  Otra pregunta vos trabajas en PHP o en otro lenguaje?

**Comment by maxivgg** [comment]
Genial @mendozada, esto me sirve para cuando tengo Comprobantes Asociados, pero nose como es la estructura del PeriodoAsoc, porque algunas notas de créditos o débito no tienen comprobantes asociados entonces necesitaba notificar el Periodo.

> hola Maxivgg , en mi estructura de datos yo tuve que agregar los datos para los Comprobantes Asociados y me resulto ,
> 
> Te pego mi codigo php de como lo hice
> `if( $bandera == 'Nc'){`
> ` $data['CbtesAsoc'] = array(`
> ` 'CbteAsoc' => array('Tipo' => $fact_asoc->Tipo,`
> ` 'PtoVta' => $fact_asoc->PtoVta,`
> ` 'Nro' => $fact_asoc->Nro,`
> ` 'Cuit' => $empresa->cuit,`
> ` 'CbteFch' => intval(date('Ymd', strtotime($fact_asoc->fecha)))`
> ` ));`
> ` }`
> ` `
> 
> Espero te sea de ayuda . saludos

**Comment by mendozada** [comment]
@maxivgg  es lo mismo , tenes que poner 

`$data['PeriodoAsoc'] = array(
'FchDesde' => intval(date('Ymd', strtotime($fact_asoc->fechadesde))),
'FchHasta' => intval(date('Ymd', strtotime($fact_asoc->fechahasta)))
);`

**Comment by maxivgg** [comment]
Estoy teniendo algun otro problema porque mando esta data y me sigue dando el mismo error

Array ( [Concepto] => 1 [DocTipo] => 80 [DocNro] => *********** [CbteDesde] => 21 [CbteHasta] => 21 [CbteFch] => 20210415 [ImpTotal] => 11892.26 [ImpTotConc] => 0 [ImpNeto] => 11892.26 [ImpOpEx] => 0 [ImpIVA] => 0 [ImpTrib] => 0 [FchServDesde] => [FchServHasta] => [FchVtoPago] => [MonId] => PES [MonCotiz] => 1 [Iva] => Array ( [AlicIva] => Array ( [0] => Array ( [Id] => 3 [BaseImp] => 11892.26 [Importe] => 0 ) ) ) [PeriodoAsoc] => Array ( [FchDesde] => 20210401 [FchHasta] => 20210430 ) ) 


stdClass Object ( [Code] => 10197 [Msg] => Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc. 

> @maxivgg es lo mismo , tenes que poner
> 
> `$data['PeriodoAsoc'] = array( 'FchDesde' => intval(date('Ymd', strtotime($fact_asoc->fechadesde))), 'FchHasta' => intval(date('Ymd', strtotime($fact_asoc->fechahasta))) );`

**Comment by arielarce2** [comment]
Buenas , estoy teniendo el mismo problema que maxivgg, con la estructura de PeriodoAsoc no la toma y da el mismo error y me pasa con una Nota de Credito A de una Factura A de este mismo mes.

**Comment by glerendegui** [comment]
Por si a alguien más le pasa, el mensaje de error requiere un campo "CbteAsoc", pero el nombre del campo extra que debemos pasar es "CbtesAsoc" (notar la "s"). Este debe ser un array de CbteAsoc, aunque este nombre es irrelevante.

**Comment by gesosa** [comment]
Hola!!
Estoy teniendo el mismo problema. Arme el areglo $data['PeriodoAsoc'] y el error que me da es el mismo " 10197 [Msg] => Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc".
Veo que a  @glerendegui le pasa lo mismo. Alguien lo soluciono?
