### ISSUE TITLE
Migracion AFIP TLS 1.2

### ISSUE THREAD

**Issue by jenanni** [AfipSDK/afip.php#83]
Hola amigos, recientemente AFIP lanzo un comunicado de que sus webservices dejaran de tener soporte para TLS 1.0 y 1.1, y se soportara solamente TLS 1.2.
El SDK actualmete funciona con TLS 1.2 o habra que hacer cambios?

Gracias!

**Comment by ivanalemunioz** [comment]
El SDK se ira actualizando a medida que Afip libere los cambios

**Comment by nancyrami** [comment]
Buenas tardes,
este tema cómo quedo? la ultima versión 0.7.x soporta TLS 1.2?
Muchas gracias :)

**Comment by ivanalemunioz** [comment]
Sisi
