### ISSUE TITLE
Descripción de Productos

### ISSUE THREAD

**Issue by johannholzmann** [AfipSDK/afip.php#85]
Buen día! Primero que nada, muchísimas gracias por este desarrollo, excelente trabajo.
Quería consultar si existe la posibilidad de crear un comprobante detallando productos y su descripción, como por ejemplo:
Producto  Cantidad  Imp. Neto  Imp Iva
Manzana   2kg            100            21
...
Así para cada tupla de productos, poder subir una descripción con su nombre, cantidad y demás atributos, básicamente modelando la factura original proveniente de la web Afip.
Muchas gracias!

**Comment by NicoMachado** [comment]
Buen dia @johannholzmann ,
hasta donde se los webservices de la AFIP no requieren esa información.

Que web service estas intentando consumir ?

Saludos

**Comment by johannholzmann** [comment]
Buenas tardes, gracias por la respuesta! 
Estoy intentando consumir el servicio "Factura Electrónica" (WSFE). Estuve revisando algunos posts y leí que este servicio no soporta el detalle de ítems, que se añadió un nuevo servicio WSMTXCA pero que este kit de desarrollo aun no lo implementa. Hay alguna posibilidad de incluir este nuevo servicio al kit? En el caso de que no, intentare crearlo yo y añadirlo, pero no se que tan complejo será.
Desde ya, muchísimas gracias!

> Buen dia @johannholzmann ,
> hasta donde se los webservices de la AFIP no requieren esa información.
> 
> Que web service estas intentando consumir ?
> 
> Saludos

**Comment by ivanalemunioz** [comment]
El tema es que el WSMTXCA  no es para que lo usen todos. Para que lo puedas usar la AFIP debe obligarte a usarlo

**Comment by johannholzmann** [comment]
Buen día! Okey, gracias entonces, veré que puedo hacer.
Otra consulta @ivanalemunioz , hay alguna forma de ver el tipo de comprobante que se crea, ósea el detallado de la factura, en modo homologación? Supongo que estos comprobantes se almacenan en una base de datos "ficticia" por así decirlo. Disculpa si es incorrecto preguntarlo en este post, saludos!

**Comment by ivanalemunioz** [comment]
Sisi con este metodo podes obtener los detalles del comprobante ya sea en test o produccion https://github.com/AfipSDK/afip.php/wiki/Facturaci%C3%B3n-Electr%C3%B3nica#obtener-informaci%C3%B3n-de-un-comprobante

**Comment by johannholzmann** [comment]
Perfecto, muchísimas gracias @ivanalemunioz !
Cierro el post.
