### ISSUE TITLE
El CEE ya posee un TA valido para el acceso al WSN solicitado

### ISSUE THREAD

**Issue by achiaramello** [AfipSDK/afip.php#86]
Cuando quiero autorizar, mas alla que el server tiene sincronizada la hora por ntp con afip, el SOAP me da el error detallado en el titulo y a continuacion copio la salida completa:

`Fatal error: Uncaught exception 'Exception' with message 'SOAP Fault: ns1:coe.alreadyAuthenticated
El CEE ya posee un TA valido para el acceso al WSN solicitado
' in /top/apache/afip/src/Afip.php:233
Stack trace:
#0 /top/apache/afip/src/Afip.php(173): Afip->CreateServiceTA('wsfe')
#1 /top/apache/afip/src/Class/ElectronicBilling.php(344): Afip->GetServiceTA('wsfe')
#2 /top/apache/afip/src/Class/ElectronicBilling.php(320): ElectronicBilling->GetWSInitialRequest('FECompUltimoAut...')
#3 /top/apache/afip/src/Class/ElectronicBilling.php(41): ElectronicBilling->ExecuteRequest('FECompUltimoAut...', Array)
#4 /top/apache/afip/factura.php(44): ElectronicBilling->GetLastVoucher(482, 1)
#5 {main}
  thrown in /top/apache/afip/src/Afip.php on line 233
`
Existe algun metodo para consultarle al SOAP si tengo un TA valido?
Gracias !

**Comment by ivanalemunioz** [comment]
No existe un metodo para sber si ya existeun TA valido

**Comment by achiaramello** [comment]
Y como soluciono el problema?

**Comment by ivanalemunioz** [comment]
El problema aparece cuando ya se genero un token y se intenta generar otro, esto es automatica, de casualidad borraste los token o estas usando el certificado en mas de un ambiente/server/pc?

**Comment by achiaramello** [comment]
Cuando uso el certificado en mas de un ambiente de produccion. El tema es que tengo 16 sucursales donde va  a correr el sistema, de una misma empresa/cuit.
Debo generar un certificado para cada sucursal? El cada sucursal tengo aprox 20 puntos de venta por cada una... seria 20 x 16

**Comment by ivanalemunioz** [comment]
Si, debes generar un certificado por cada server/pc que tengas, no pueden compartir el mismo certificado

**Comment by achiaramello** [comment]
Excelente. Gracias !
