### ISSUE TITLE
Dice "Computador no autorizado" pero los certificados estan al día siendo utilizados por otro sistema ya

### ISSUE THREAD

**Issue by AcidBurn86** [AfipSDK/afip.php#87]
Estoy usando certificado y key validas que estan ahora mismo en producción, lo uso ahora mismo para facturar en otro sistema, pero acá me dice computador no autorizado. Hace falta adherir algún otro servicio o relación aparte de los conocidos como "factura electronica" "rear/rece" etc ?

Error:
`"Fatal error: Uncaught Exception: SOAP Fault: ns1:coe.notAuthorized Computador no autorizado a acceder al servicio in \afip\Afip.php:233 ...."`

PHP:

```
include 'afip/Afip.php';
$afip = new Afip(array('CUIT' => 20322213043,'production' => true,'passphrase' => 1));
$taxpayer_details = $afip->RegisterScopeThirteen->GetTaxpayerDetails(20322213043); 

print_r($taxpayer_details);
```

**Comment by ivanalemunioz** [comment]
Para poder utilizar el web service debes vincular el servicio de consulta al padron alcance 13 con el certificado

**Comment by KatiaSishost** [comment]
debes activar SOAP en php.ini y luego vas al panel de la afip donde asignas los certificados y debes vincularlos! luego de crear el certificado debes decirles que accesos tienen, debes seleccionar el que dice factura electronica!

**Comment by jcpatio** [comment]
si estas en la parte de pruebas el error es porque  no hiciste la autorización.

si te encuentras en producción el error es  la asignación del certificado y la relación en la afip
