### ISSUE TITLE
cert.untrusted Certificado no emitido por AC de confianza

### ISSUE THREAD

**Issue by Hugo939** [AfipSDK/afip.php#88]
Hola, al utilizar el archivo crt que emite afip desde "Administración de certificados digitales" me indica que no es un certificado válido

**Comment by ivanalemunioz** [comment]
Si es un certificado de produccion tenes que agregar el parametro `production => true` al hacer un `new Afip()`

**Comment by Niko-EstudioBL** [comment]
Buen día. Perdón por reabrir el hilo, pero me encuentro con este mismo inconveniente empleando el .crt emitido por AFIP desde "Administración de certificados digitales". Me indica que no es un certificado válido, y al agregar el parámetro `production => true` simplemente recibo un **500 Internal Server Error**

**Comment by ivanalemunioz** [comment]
En el código

https://docs.afipsdk.com/paso-a-paso/como-usarlo#paso-2-crear-una-instancia-clase-afip
