### ISSUE TITLE
Comprobantes en línea y condiciones de venta

### ISSUE THREAD

**Issue by Gabrielmirano** [AfipSDK/afip.php#91]
Buenos días, la librería parece funcionar correctamente. 

--> Retorna el CAE
--> Retorna fecha de vencimiento del CAE
--> Retorna número del comprobante
--> Al chequear la información con el método GetVoucherInfo devuelve un arreglo con todos los datos correctamente.

Sin embargo, al ingresar a la sección "Regimen de comprobantes en línea" (AFIP) y realizar una consulta de comprobantes no aparece ninguno. ¿A qué se debe?
-------
¿Es posible agregar la condición de venta(Contado, tarjeta, cheque, etc...)?

**Comment by guillebalmacedaonline** [comment]
Hola buen dia. Las facturas emitidas por webservice aparecen en mis comprobantes.

Saludos.

**Comment by Gabrielmirano** [comment]
> 
> 
> Hola buen dia. Las facturas emitidas por webservice aparecen en mis comprobantes.
> 
> Saludos.

No encuentro una sección con ese nombre, ¿Hay que adherir servicio?

**Comment by Gabrielmirano** [comment]
Ya encontré, había que adherir el servicio en Administrador de relaciones de clave fiscal > Adherir servicio > AFIP > Servicios interactivos > Mis comprobantes.

Gracias.
