### ISSUE TITLE
Que hace el metodo CreateNextVoucher?

### ISSUE THREAD

**Issue by hugomonaco** [AfipSDK/afip.php#92]
Hola, estoy empezando a implementar la libreria en un sistema Laravel, y leyendo la documentacion me encontre con el metodo **CreateNextVoucher**. En un primer momento por el nombre del metodo supuse que generaria el comprobante sin necesidad de pasarle el numero, es decir, genera el siguiente comprobante calculando el numero automaticamente, pero en la misma documetnacion dice que requiere los mismos datos que el metodo **CreateVoucher**, por lo que asumo que hay que pasarle el numero de comprobante. 
Entonces, ¿Que hace este metodo?  

Muchas gracias.

**Comment by ivanalemunioz** [comment]
Hace exacto lo que decis, no es necesario pasarle el numero de comprobante

**Comment by hugomonaco** [comment]
Genial, me viene bárbaro entonces, gracias por responder
