### ISSUE TITLE
Punto de Venta

### ISSUE THREAD

**Issue by diegobiasatti** [AfipSDK/afip.php#93]
Estimados, me surge la duda.. si cuando todavía estoy en Testing usando AfipSDK, debo tener un punto de venta en modo testing. 
O solo se puede crear un punto de venta normal dentro de la Afip, y usarlo para testing y es el mismo que luego se usa en producción. 

Desde ya muchas gracias.

**Comment by elmaxid** [comment]
Hola, como estas?
Te cuento en base a mi experiencia; en dev el punto de venta lo pones vos, arbitrario. Para producción tenes que dar de alta el punto de venta para el webservice.
abrazo
M.

**Comment by diegobiasatti** [comment]
voy a probar con esto que me decis, realmente no probe de poner cualquiera. Los tengo al tanto muchas gracias

**Comment by diegobiasatti** [comment]
> Hola, como estas?
> Te cuento en base a mi experiencia; en dev el punto de venta lo pones vos, arbitrario. Para producción tenes que dar de alta el punto de venta para el webservice.
> abrazo
> M.


Estabas en toda la razon muchas gracias!! funciono correctamente.
Saludos!
