### ISSUE TITLE
Errores en producción

### ISSUE THREAD

**Issue by Hugo939** [AfipSDK/afip.php#94]
Hola, en local me funciona todo bien pero al subirlo a un servidor en la nube me tira esta serie de errores

Warning: SimpleXMLElement::asXML(/var/www/html/src/Afip_res/TRA-23381659399-wsfe.xml): failed to open stream: Permission denied in /var/www/html/src/Afip.php on line 202

Warning: openssl_pkcs7_sign(): error opening input file /var/www/html/src/Afip_res/TRA-23381659399-wsfe.xml! in /var/www/html/src/Afip.php on line 208

Notice: Trying to get property 'token' of non-object in /var/www/html/src/Class/ElectronicBilling.php on line 332

Notice: Trying to get property 'sign' of non-object in /var/www/html/src/Class/ElectronicBilling.php on line 333

Fatal error: Uncaught Exception: (600) ValidacionDeToken: Parametro nulo o vacio (token) in /var/www/html/src/Class/ElectronicBilling.php:364 Stack trace: #0 /var/www/html/src/Class/ElectronicBilling.php(308): ElectronicBilling->_CheckErrors() #1 /var/www/html/src/Class/ElectronicBilling.php(41): ElectronicBilling->ExecuteRequest() #2 /var/www/html/src/Class/ElectronicBilling.php(122): ElectronicBilling->GetLastVoucher() #3 /var/www/html/pruebafip.php(47): ElectronicBilling->CreateNextVoucher() #4 {main} thrown in /var/www/html/src/Class/ElectronicBilling.php on line 364

me cansé de darle permisos, no se me ocurre qué más hacer

**Comment by ivanalemunioz** [comment]
Hola Hugo, parece algun problema de permisos, pudiste resolverlo?

**Comment by Hugo939** [comment]
> Hola Hugo, parece algun problema de permisos, pudiste resolverlo?

No, todavía no!

**Comment by KatiaSishost** [comment]
elimina el archivo xml y volve a subirlo, revisa los permiso de LAS CARPETAS!
