### ISSUE TITLE
Duda multi certificado, Hardcodear ubicación!

### ISSUE THREAD

**Issue by KatiaSishost** [AfipSDK/afip.php#96]
Hola hoy comencé a usar esta sdk, muy buena y facil de utilizar por cierto, a pesar del lio que es la AFIP en si...

Estoy usando Laravel con un modo multi-inquilino

Alguien sería tan amable de decirme como hardcodear con el archivo example... por ejemplo...

si en lugar de encontrarse mi certificado y key en "vendor/afipsdk/src/Afip_res" como normalmente se encuentra... que esté por ejemplo.. en:

yo obtengo la ruta exacta del usuario que está activo con $usuario->getName

y mis certificados quisiera que se recuperaran de la rutas:
storage/app/res/Usuario1
storage/app/res/Usuario2

Obviamente teniendo Usuario1 y Usuario2... sus respectivos certificados.

Por otro lado, creo que esto es imposible pero pregunto igualmente, se puede guardar los certificados en la base de datos? o si o si tiene que ser un archivo?

**Comment by NicoMachado** [comment]
Creo que esto te puede servir,
entiendo que la información que necesitas parametrizar se puede indicar por parámetros al constructor.

![image](https://user-images.githubusercontent.com/23136927/113579519-ce462c00-95fa-11eb-92b0-0c5ea1feb725.png)

Saludos

**Comment by KatiaSishost** [comment]
Perfectisimo, muchisimas gracias!
