### ISSUE TITLE
Productos?

### ISSUE THREAD

**Issue by KatiaSishost** [AfipSDK/afip.php#97]
Despues de hacer todo me di cuenta que este sdk solo envia el total y el importe de iva nomas... pero... los productos que se venden donde se envian? para luego descargar la factura electrónica? o eso es unicamente si cargas los datos desde la app de la afip... y de acá debes almacenar los datos tu mismo?

**Comment by juanledesma** [comment]
Buenas, los ítems vendidos los agregas vos a la factura. Tendrías que tener una tabla con dichos productos, para tener un control o por si necesitas re imprimir la factura.El 4 abr. 2021 12:39, KatiaSishost ***@***.***> escribió:

Despues de hacer todo me di cuenta que este sdk solo envia el total y el importe de iva nomas... pero... los productos que se venden donde se envian? para luego descargar la factura electrónica? o eso es unicamente si cargas los datos desde la app de la afip... y de acá debes almacenar los datos tu mismo?

**Comment by AndyGotfridt** [comment]
Exacto, debes almacenar header y body de la factura y en caso de necesitar imprimir nuevamente dicho comprobante lo regeneras con los datos almacenados

**Comment by KatiaSishost** [comment]
Ah, perfecto pense que esto se enviaba y almacenaba todo como el facturador que tiene la afip misma.
Muchisimas gracias!

**Comment by KatiaSishost** [comment]
Ah, perfecto pense que esto se enviaba y almacenaba todo como el facturador que tiene la afip misma.
Muchisimas gracias!
