### ISSUE TITLE
Error Sitio Blanco.

### ISSUE THREAD

**Issue by EscuderoKevin93** [AfipSDK/afip.php#99]
Hola ! bueno de ante manos gracias por la sdk.

Tengo problemas va generar un certificado es re complicado no se si lo genere bien porque hay 2 partes donde se puede hacer jaja.

Lo del openssl lo hice en la PC donde tengo el XAMPP obtuve el Pedido y la Key. Subi el pedido a la web -> https://wsass-homo.afip.gob.ar/wsass/portal/main.aspx que me dio el certificado solo para verlo no bajarlo copie el "Certificado" manualmente y lo pegue en el archivo .cert y la key que use para pedirlo en el otro archivo.

Hice un archivo para probar ya que no se si esta en MODO TEST o PRODUCCION.

	$afip = new Afip(array('CUIT' => MI CUIT));
	$sales_points = $afip->ElectronicBilling->GetSalesPoints();
	print_r($sales_points);

Tarda como 10 segundos 

Fatal error: Uncaught Exception: (602) Sin Resultados: - Metodo FEParamGetPtosVenta in C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Class\ElectronicBilling.php:380 Stack trace: #0 C:\xampp\htdocs\kevin\afip\afipsdk\afip.php\src\Class\ElectronicBilling.php(324): ElectronicBilling->_CheckErrors('FEParamGetPtosV...', Object(stdClass)) #1

Despues en la parte de la web principal de la AFIP.

Administración de Certificados Digitales  el cual tambien puse mi certificado y ahi se me dejo bajar el .cert el cual instale y tambien probe pegandolo manualmente en el archivo cert

La verdad esta muy buena la sdk pero la afip sigue siendo pesima...

Agradezco toda ayuda de ante mano , tambien si alguien ya lo hizo y me quiere cobrar por el servicio de ayudarme a hacer todo esto de los certificados y eso dejo mi email escuderokevin93@gmail.com

Saludos, que tengan buen dia!

**Comment by ivanalemunioz** [comment]
Parece que esta todo bien, el error "Uncaught Exception: (602) Sin Resultados" sale porque en test no hay puntos de venta, deberias probar con algun otro metodo, proba crear un comprobante. 

Mientras el sdk no tenga el parametro `production => TRUE` quiere decir que esta en modo test. De todas formas para usar el modo produccion necesitas certificados de produccion que no son los mismos ni se obtienen de la misma forma asique quedate tranquilo que lo que hagas en test no es real

**Comment by Askeshine** [comment]
> 
> 
> Parece que esta todo bien, el error "Uncaught Exception: (602) Sin Resultados" sale porque en test no hay puntos de venta, deberias probar con algun otro metodo, proba crear un comprobante.
> 
> Mientras el sdk no tenga el parametro `production => TRUE` quiere decir que esta en modo test. De todas formas para usar el modo produccion necesitas certificados de produccion que no son los mismos ni se obtienen de la misma forma asique quedate tranquilo que lo que hagas en test no es real


Genial muchas gracias, ahora en un ratito pruebo y te comento por aca como me fue.

**Comment by Askeshine** [comment]
Podes cerrar el issue funciona tal cual decis, ♥
